# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Blocks")

model.instance <- Blocks$new()

test_that("next_page", {
  # tests for the property `next_page` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`next_page`, "EXPECTED_RESULT")
})

test_that("blocks", {
  # tests for the property `blocks` (array[Block])

  # uncomment below to test the property 
  #expect_equal(model.instance$`blocks`, "EXPECTED_RESULT")
})

