# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Entity")

model.instance <- Entity$new()

test_that("entity", {
  # tests for the property `entity` (integer)
  # Entity id

  # uncomment below to test the property 
  #expect_equal(model.instance$`entity`, "EXPECTED_RESULT")
})

test_that("balance", {
  # tests for the property `balance` (Values)

  # uncomment below to test the property 
  #expect_equal(model.instance$`balance`, "EXPECTED_RESULT")
})

test_that("first_tx", {
  # tests for the property `first_tx` (TxSummary)

  # uncomment below to test the property 
  #expect_equal(model.instance$`first_tx`, "EXPECTED_RESULT")
})

test_that("last_tx", {
  # tests for the property `last_tx` (TxSummary)

  # uncomment below to test the property 
  #expect_equal(model.instance$`last_tx`, "EXPECTED_RESULT")
})

test_that("in_degree", {
  # tests for the property `in_degree` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`in_degree`, "EXPECTED_RESULT")
})

test_that("out_degree", {
  # tests for the property `out_degree` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`out_degree`, "EXPECTED_RESULT")
})

test_that("no_addresses", {
  # tests for the property `no_addresses` (integer)
  # number of contained addresses

  # uncomment below to test the property 
  #expect_equal(model.instance$`no_addresses`, "EXPECTED_RESULT")
})

test_that("no_incoming_txs", {
  # tests for the property `no_incoming_txs` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`no_incoming_txs`, "EXPECTED_RESULT")
})

test_that("no_outgoing_txs", {
  # tests for the property `no_outgoing_txs` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`no_outgoing_txs`, "EXPECTED_RESULT")
})

test_that("total_received", {
  # tests for the property `total_received` (Values)

  # uncomment below to test the property 
  #expect_equal(model.instance$`total_received`, "EXPECTED_RESULT")
})

test_that("total_spent", {
  # tests for the property `total_spent` (Values)

  # uncomment below to test the property 
  #expect_equal(model.instance$`total_spent`, "EXPECTED_RESULT")
})

test_that("tags", {
  # tests for the property `tags` (Tags)

  # uncomment below to test the property 
  #expect_equal(model.instance$`tags`, "EXPECTED_RESULT")
})

