# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AddressTx")

model.instance <- AddressTx$new()

test_that("currency_type", {
  # tests for the property `currency_type` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`currency_type`, "EXPECTED_RESULT")
})

test_that("height", {
  # tests for the property `height` (integer)
  # Height

  # uncomment below to test the property 
  #expect_equal(model.instance$`height`, "EXPECTED_RESULT")
})

test_that("timestamp", {
  # tests for the property `timestamp` (integer)
  # Timestamp

  # uncomment below to test the property 
  #expect_equal(model.instance$`timestamp`, "EXPECTED_RESULT")
})

test_that("tx_hash", {
  # tests for the property `tx_hash` (character)
  # Transaction hash

  # uncomment below to test the property 
  #expect_equal(model.instance$`tx_hash`, "EXPECTED_RESULT")
})

test_that("value", {
  # tests for the property `value` (Values)

  # uncomment below to test the property 
  #expect_equal(model.instance$`value`, "EXPECTED_RESULT")
})

test_that("values", {
  # tests for the property `values` (Values)

  # uncomment below to test the property 
  #expect_equal(model.instance$`values`, "EXPECTED_RESULT")
})

