# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Values")

model.instance <- Values$new()

test_that("eur", {
  # tests for the property `eur` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`eur`, "EXPECTED_RESULT")
})

test_that("usd", {
  # tests for the property `usd` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`usd`, "EXPECTED_RESULT")
})

test_that("value", {
  # tests for the property `value` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`value`, "EXPECTED_RESULT")
})

