# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TxsApi")

api.instance <- TxsApi$new()

test_that("GetTx", {
  # tests for GetTx
  # base path: https://api.graphsense.info
  # Returns details of a specific transaction identified by its hash.
  # @param currency character The cryptocurrency (e.g., btc)
  # @param tx.hash character The transaction hash
  # @return [Tx]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListTxs", {
  # tests for ListTxs
  # base path: https://api.graphsense.info
  # Returns transactions
  # @param currency character The cryptocurrency (e.g., btc)
  # @param page character Resumption token for retrieving the next page (optional)
  # @return [Txs]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

