# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Taxonomy")

model.instance <- Taxonomy$new()

test_that("taxonomy", {
  # tests for the property `taxonomy` (character)
  # Taxonomy

  # uncomment below to test the property 
  #expect_equal(model.instance$`taxonomy`, "EXPECTED_RESULT")
})

test_that("uri", {
  # tests for the property `uri` (character)
  # URI

  # uncomment below to test the property 
  #expect_equal(model.instance$`uri`, "EXPECTED_RESULT")
})

