# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Concept")

model.instance <- Concept$new()

test_that("label", {
  # tests for the property `label` (character)
  # Label

  # uncomment below to test the property 
  #expect_equal(model.instance$`label`, "EXPECTED_RESULT")
})

test_that("taxonomy", {
  # tests for the property `taxonomy` (character)
  # Taxonomy

  # uncomment below to test the property 
  #expect_equal(model.instance$`taxonomy`, "EXPECTED_RESULT")
})

test_that("uri", {
  # tests for the property `uri` (character)
  # URI

  # uncomment below to test the property 
  #expect_equal(model.instance$`uri`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)
  # Description

  # uncomment below to test the property 
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (character)
  # ID

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

