# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Entities")

model.instance <- Entities$new()

test_that("next_page", {
  # tests for the property `next_page` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`next_page`, "EXPECTED_RESULT")
})

test_that("entities", {
  # tests for the property `entities` (array[Entity])

  # uncomment below to test the property 
  #expect_equal(model.instance$`entities`, "EXPECTED_RESULT")
})

