# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Rates")

model.instance <- Rates$new()

test_that("height", {
  # tests for the property `height` (integer)
  # Height

  # uncomment below to test the property 
  #expect_equal(model.instance$`height`, "EXPECTED_RESULT")
})

test_that("rates", {
  # tests for the property `rates` (RatesRates)

  # uncomment below to test the property 
  #expect_equal(model.instance$`rates`, "EXPECTED_RESULT")
})

