# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AddressAndEntityTags")

model.instance <- AddressAndEntityTags$new()

test_that("address_tags", {
  # tests for the property `address_tags` (array[AddressTag])
  # First page of address tags of this entity

  # uncomment below to test the property 
  #expect_equal(model.instance$`address_tags`, "EXPECTED_RESULT")
})

test_that("entity_tags", {
  # tests for the property `entity_tags` (array[EntityTag])
  # First page of entity tags of this entity

  # uncomment below to test the property 
  #expect_equal(model.instance$`entity_tags`, "EXPECTED_RESULT")
})

