# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test StatsVersion")

model.instance <- StatsVersion$new()

test_that("nr", {
  # tests for the property `nr` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`nr`, "EXPECTED_RESULT")
})

test_that("hash", {
  # tests for the property `hash` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`hash`, "EXPECTED_RESULT")
})

test_that("timestamp", {
  # tests for the property `timestamp` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`timestamp`, "EXPECTED_RESULT")
})

test_that("file", {
  # tests for the property `file` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`file`, "EXPECTED_RESULT")
})

