# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Neighbors")

model.instance <- Neighbors$new()

test_that("next_page", {
  # tests for the property `next_page` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`next_page`, "EXPECTED_RESULT")
})

test_that("neighbors", {
  # tests for the property `neighbors` (array[Neighbor])

  # uncomment below to test the property 
  #expect_equal(model.instance$`neighbors`, "EXPECTED_RESULT")
})

