# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AddressTags")

model.instance <- AddressTags$new()

test_that("address_tags", {
  # tests for the property `address_tags` (array[AddressTag])

  # uncomment below to test the property 
  #expect_equal(model.instance$`address_tags`, "EXPECTED_RESULT")
})

test_that("next_page", {
  # tests for the property `next_page` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`next_page`, "EXPECTED_RESULT")
})

