# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BatchResponse")

model.instance <- BatchResponse$new()

test_that("operation", {
  # tests for the property `operation` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`operation`, "EXPECTED_RESULT")
})

test_that("result", {
  # tests for the property `result` (array[GetTxIoResult])

  # uncomment below to test the property 
  #expect_equal(model.instance$`result`, "EXPECTED_RESULT")
})

