# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test StatsTool")

model.instance <- StatsTool$new()

test_that("visible_name", {
  # tests for the property `visible_name` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`visible_name`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("version", {
  # tests for the property `version` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`version`, "EXPECTED_RESULT")
})

test_that("titanium_replayable", {
  # tests for the property `titanium_replayable` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`titanium_replayable`, "EXPECTED_RESULT")
})

test_that("responsible_for", {
  # tests for the property `responsible_for` (array[character])

  # uncomment below to test the property 
  #expect_equal(model.instance$`responsible_for`, "EXPECTED_RESULT")
})

