# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test EntityTags")

model.instance <- EntityTags$new()

test_that("entity_tags", {
  # tests for the property `entity_tags` (array[EntityTag])

  # uncomment below to test the property 
  #expect_equal(model.instance$`entity_tags`, "EXPECTED_RESULT")
})

test_that("next_page", {
  # tests for the property `next_page` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`next_page`, "EXPECTED_RESULT")
})

