# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Rate")

model.instance <- Rate$new()

test_that("code", {
  # tests for the property `code` (character)
  # iso currency code

  # uncomment below to test the property 
  #expect_equal(model.instance$`code`, "EXPECTED_RESULT")
})

test_that("value", {
  # tests for the property `value` (numeric)
  # exchange rate

  # uncomment below to test the property 
  #expect_equal(model.instance$`value`, "EXPECTED_RESULT")
})

