# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test LinkUtxo")

model.instance <- LinkUtxo$new()

test_that("currency_type", {
  # tests for the property `currency_type` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`currency_type`, "EXPECTED_RESULT")
})

test_that("tx_hash", {
  # tests for the property `tx_hash` (character)
  # Transaction hash

  # uncomment below to test the property 
  #expect_equal(model.instance$`tx_hash`, "EXPECTED_RESULT")
})

test_that("height", {
  # tests for the property `height` (integer)
  # Height

  # uncomment below to test the property 
  #expect_equal(model.instance$`height`, "EXPECTED_RESULT")
})

test_that("timestamp", {
  # tests for the property `timestamp` (integer)
  # Timestamp

  # uncomment below to test the property 
  #expect_equal(model.instance$`timestamp`, "EXPECTED_RESULT")
})

test_that("input_value", {
  # tests for the property `input_value` (Values)

  # uncomment below to test the property 
  #expect_equal(model.instance$`input_value`, "EXPECTED_RESULT")
})

test_that("output_value", {
  # tests for the property `output_value` (Values)

  # uncomment below to test the property 
  #expect_equal(model.instance$`output_value`, "EXPECTED_RESULT")
})

