# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test StatsLedgerVersion")

model.instance <- StatsLedgerVersion$new()

test_that("nr", {
  # tests for the property `nr` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`nr`, "EXPECTED_RESULT")
})

test_that("timestamp", {
  # tests for the property `timestamp` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`timestamp`, "EXPECTED_RESULT")
})

