# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test EntitiesApi")

api.instance <- EntitiesApi$new()

test_that("GetEntity", {
  # tests for GetEntity
  # base path: https://api.graphsense.info
  # Get an entity, optionally with tags
  # @param currency character The cryptocurrency (e.g., btc)
  # @param entity integer The entity ID
  # @param include.tags character Whether tags should be included (optional)
  # @param tag.coherence character Whether to calculate coherence of address tags (optional)
  # @return [Entity]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListEntities", {
  # tests for ListEntities
  # base path: https://api.graphsense.info
  # Get entities
  # @param currency character The cryptocurrency (e.g., btc)
  # @param ids array[character] Restrict result to given set of comma separated IDs (optional)
  # @param page character Resumption token for retrieving the next page (optional)
  # @param pagesize integer Number of items returned in a single page (optional)
  # @return [Entities]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListEntitiesCsv", {
  # tests for ListEntitiesCsv
  # base path: https://api.graphsense.info
  # Get entities as CSV
  # @param currency character The cryptocurrency (e.g., btc)
  # @param ids array[character] Set of comma separated IDs
  # @return [character]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListEntityAddresses", {
  # tests for ListEntityAddresses
  # base path: https://api.graphsense.info
  # Get an entity&#39;s addresses
  # @param currency character The cryptocurrency (e.g., btc)
  # @param entity integer The entity ID
  # @param page character Resumption token for retrieving the next page (optional)
  # @param pagesize integer Number of items returned in a single page (optional)
  # @return [EntityAddresses]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListEntityAddressesCsv", {
  # tests for ListEntityAddressesCsv
  # base path: https://api.graphsense.info
  # Get an entity&#39;s addresses as CSV
  # @param currency character The cryptocurrency (e.g., btc)
  # @param entity integer The entity ID
  # @return [character]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListEntityNeighbors", {
  # tests for ListEntityNeighbors
  # base path: https://api.graphsense.info
  # Get an entity&#39;s neighbors in the entity graph
  # @param currency character The cryptocurrency (e.g., btc)
  # @param entity integer The entity ID
  # @param direction character Incoming or outgoing neighbors
  # @param ids array[character] Restrict result to given set of comma separated IDs (optional)
  # @param include.labels character Whether labels of tags should be included (optional)
  # @param page character Resumption token for retrieving the next page (optional)
  # @param pagesize integer Number of items returned in a single page (optional)
  # @return [Neighbors]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListEntityNeighborsCsv", {
  # tests for ListEntityNeighborsCsv
  # base path: https://api.graphsense.info
  # Get an entity&#39;s neighbors in the entity graph as CSV
  # @param currency character The cryptocurrency (e.g., btc)
  # @param entity integer The entity ID
  # @param direction character Incoming or outgoing neighbors
  # @param include.labels character Whether labels of tags should be included (optional)
  # @return [character]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListTagsByEntity", {
  # tests for ListTagsByEntity
  # base path: https://api.graphsense.info
  # Get tags for a given entity
  # @param currency character The cryptocurrency (e.g., btc)
  # @param entity integer The entity ID
  # @param tag.coherence character Whether to calculate coherence of address tags (optional)
  # @return [Tags]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListTagsByEntityByLevelCsv", {
  # tests for ListTagsByEntityByLevelCsv
  # base path: https://api.graphsense.info
  # Get address or entity tags for a given entity as CSV
  # @param currency character The cryptocurrency (e.g., btc)
  # @param entity integer The entity ID
  # @param level character Whether tags on the address or entity level are requested
  # @return [character]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SearchEntityNeighbors", {
  # tests for SearchEntityNeighbors
  # base path: https://api.graphsense.info
  # Search deeply for matching neighbors
  # @param currency character The cryptocurrency (e.g., btc)
  # @param entity integer The entity ID
  # @param direction character Incoming or outgoing neighbors
  # @param key character Match neighbors against one and only one of these properties: - the category the entity belongs to - addresses the entity contains - entity ids - total_received: amount the entity received in total - balance: amount the entity holds finally
  # @param value array[character] If key is - category: comma separated list of category names - addresses: comma separated list of address IDs - entities: comma separated list of entity IDs - total_received/balance: comma separated tuple of (currency, min, max)
  # @param depth integer How many hops should the transaction graph be searched
  # @param breadth integer How many siblings of each neighbor should be tried (optional)
  # @param skip.num.addresses integer Skip entities containing more addresses (optional)
  # @return [array[SearchResultLevel1]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

