# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TagsApi")

api.instance <- TagsApi$new()

test_that("ListConcepts", {
  # tests for ListConcepts
  # base path: https://api.graphsense.info
  # Returns the supported concepts of a taxonomy
  # @param taxonomy character The taxonomy
  # @return [array[Concept]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListTags", {
  # tests for ListTags
  # base path: https://api.graphsense.info
  # Returns address and entity tags associated with a given label
  # @param label character The label of an entity
  # @param currency character The cryptocurrency (e.g., btc) (optional)
  # @return [array[Tags]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListTaxonomies", {
  # tests for ListTaxonomies
  # base path: https://api.graphsense.info
  # Returns the supported taxonomies
  # @return [array[Taxonomy]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

