# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test GetTxIoParameters")

model.instance <- GetTxIoParameters$new()

test_that("io", {
  # tests for the property `io` (Io)

  # uncomment below to test the property 
  #expect_equal(model.instance$`io`, "EXPECTED_RESULT")
})

test_that("tx_hash", {
  # tests for the property `tx_hash` (character)
  # Transaction hash

  # uncomment below to test the property 
  #expect_equal(model.instance$`tx_hash`, "EXPECTED_RESULT")
})

