# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Tags")

model.instance <- Tags$new()

test_that("address_tags", {
  # tests for the property `address_tags` (array[AddressTag])
  # Aggregated tags of contained addresses

  # uncomment below to test the property 
  #expect_equal(model.instance$`address_tags`, "EXPECTED_RESULT")
})

test_that("entity_tags", {
  # tests for the property `entity_tags` (array[EntityTag])
  # Tags of this entity

  # uncomment below to test the property 
  #expect_equal(model.instance$`entity_tags`, "EXPECTED_RESULT")
})

test_that("tag_coherence", {
  # tests for the property `tag_coherence` (numeric)
  # Tag coherence

  # uncomment below to test the property 
  #expect_equal(model.instance$`tag_coherence`, "EXPECTED_RESULT")
})

