# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Stats")

model.instance <- Stats$new()

test_that("currencies", {
  # tests for the property `currencies` (array[CurrencyStats])

  # uncomment below to test the property 
  #expect_equal(model.instance$`currencies`, "EXPECTED_RESULT")
})

test_that("version", {
  # tests for the property `version` (StatsVersion)

  # uncomment below to test the property 
  #expect_equal(model.instance$`version`, "EXPECTED_RESULT")
})

test_that("tools", {
  # tests for the property `tools` (array[StatsTool])

  # uncomment below to test the property 
  #expect_equal(model.instance$`tools`, "EXPECTED_RESULT")
})

test_that("tags_source", {
  # tests for the property `tags_source` (StatsTagsSource)

  # uncomment below to test the property 
  #expect_equal(model.instance$`tags_source`, "EXPECTED_RESULT")
})

test_that("notes", {
  # tests for the property `notes` (array[StatsNote])

  # uncomment below to test the property 
  #expect_equal(model.instance$`notes`, "EXPECTED_RESULT")
})

