# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TxValue")

model.instance <- TxValue$new()

test_that("address", {
  # tests for the property `address` (array[character])

  # uncomment below to test the property 
  #expect_equal(model.instance$`address`, "EXPECTED_RESULT")
})

test_that("value", {
  # tests for the property `value` (Values)

  # uncomment below to test the property 
  #expect_equal(model.instance$`value`, "EXPECTED_RESULT")
})

