# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test EntityTagAllOf")

model.instance <- EntityTagAllOf$new()

test_that("entity", {
  # tests for the property `entity` (integer)
  # Entity id

  # uncomment below to test the property 
  #expect_equal(model.instance$`entity`, "EXPECTED_RESULT")
})

