# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test GetTx")

model.instance <- GetTx$new()

test_that("api", {
  # tests for the property `api` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`api`, "EXPECTED_RESULT")
})

test_that("operation", {
  # tests for the property `operation` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`operation`, "EXPECTED_RESULT")
})

test_that("parameters", {
  # tests for the property `parameters` (array[GetTxParameters])

  # uncomment below to test the property 
  #expect_equal(model.instance$`parameters`, "EXPECTED_RESULT")
})

