# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test GetTxParameters")

model.instance <- GetTxParameters$new()

test_that("tx_hash", {
  # tests for the property `tx_hash` (character)
  # Transaction hash

  # uncomment below to test the property 
  #expect_equal(model.instance$`tx_hash`, "EXPECTED_RESULT")
})

