# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BulkApi")

api.instance <- BulkApi$new()

test_that("BulkCsv", {
  # tests for BulkCsv
  # base path: https://api.graphsense.info
  # Get data as CSV in bulk
  # @param currency character The cryptocurrency (e.g., btc)
  # @param api character The api of the operation to execute in bulk
  # @param operation character The operation to execute in bulk
  # @param body object Map of the operation's parameter names to (arrays of) values
  # @return [character]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("BulkJson", {
  # tests for BulkJson
  # base path: https://api.graphsense.info
  # Get data as JSON in bulk
  # @param currency character The cryptocurrency (e.g., btc)
  # @param api character The api of the operation to execute in bulk
  # @param operation character The operation to execute in bulk
  # @param body object Map of the operation's parameter names to (arrays of) values
  # @return [array[map(object)]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

