# GraphSense API
#
# GraphSense API
#
# The version of the OpenAPI document: 0.5
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title AddressTagAllOf
#'
#' @description AddressTagAllOf Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field address  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
AddressTagAllOf <- R6::R6Class(
  'AddressTagAllOf',
  public = list(
    `address` = NULL,
    initialize = function(
        `address`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`address`)) {
        stopifnot(is.character(`address`), length(`address`) == 1)
        self$`address` <- `address`
      }
    },
    toJSON = function() {
      AddressTagAllOfObject <- list()
      if (!is.null(self$`address`)) {
        AddressTagAllOfObject[['address']] <-
          self$`address`
      }

      AddressTagAllOfObject
    },
    fromJSON = function(AddressTagAllOfJson) {
      AddressTagAllOfObject <- jsonlite::fromJSON(AddressTagAllOfJson)
      if (!is.null(AddressTagAllOfObject$`address`)) {
        self$`address` <- AddressTagAllOfObject$`address`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`address`)) {
        sprintf(
        '"address":
          "%s"
                ',
        self$`address`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(AddressTagAllOfJson) {
      AddressTagAllOfObject <- jsonlite::fromJSON(AddressTagAllOfJson)
      self$`address` <- AddressTagAllOfObject$`address`
      self
    }
  )
)

