# GraphSense API
#
# GraphSense API
#
# The version of the OpenAPI document: 0.5
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title AddressTxUtxo
#'
#' @description AddressTxUtxo Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field currency_type  character 
#'
#' @field height  integer 
#'
#' @field timestamp  integer 
#'
#' @field tx_hash  character 
#'
#' @field value  \link{Values} 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
AddressTxUtxo <- R6::R6Class(
  'AddressTxUtxo',
  public = list(
    `currency_type` = NULL,
    `height` = NULL,
    `timestamp` = NULL,
    `tx_hash` = NULL,
    `value` = NULL,
    initialize = function(
        `currency_type`, `height`, `timestamp`, `tx_hash`, `value`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`currency_type`)) {
        stopifnot(is.character(`currency_type`), length(`currency_type`) == 1)
        self$`currency_type` <- `currency_type`
      }
      if (!missing(`height`)) {
        stopifnot(is.numeric(`height`), length(`height`) == 1)
        self$`height` <- `height`
      }
      if (!missing(`timestamp`)) {
        stopifnot(is.numeric(`timestamp`), length(`timestamp`) == 1)
        self$`timestamp` <- `timestamp`
      }
      if (!missing(`tx_hash`)) {
        stopifnot(is.character(`tx_hash`), length(`tx_hash`) == 1)
        self$`tx_hash` <- `tx_hash`
      }
      if (!missing(`value`)) {
        stopifnot(R6::is.R6(`value`))
        self$`value` <- `value`
      }
    },
    toJSON = function() {
      AddressTxUtxoObject <- list()
      if (!is.null(self$`currency_type`)) {
        AddressTxUtxoObject[['currency_type']] <-
          self$`currency_type`
      }
      if (!is.null(self$`height`)) {
        AddressTxUtxoObject[['height']] <-
          self$`height`
      }
      if (!is.null(self$`timestamp`)) {
        AddressTxUtxoObject[['timestamp']] <-
          self$`timestamp`
      }
      if (!is.null(self$`tx_hash`)) {
        AddressTxUtxoObject[['tx_hash']] <-
          self$`tx_hash`
      }
      if (!is.null(self$`value`)) {
        AddressTxUtxoObject[['value']] <-
          self$`value`$toJSON()
      }

      AddressTxUtxoObject
    },
    fromJSON = function(AddressTxUtxoJson) {
      AddressTxUtxoObject <- jsonlite::fromJSON(AddressTxUtxoJson)
      if (!is.null(AddressTxUtxoObject$`currency_type`)) {
        self$`currency_type` <- AddressTxUtxoObject$`currency_type`
      }
      if (!is.null(AddressTxUtxoObject$`height`)) {
        self$`height` <- AddressTxUtxoObject$`height`
      }
      if (!is.null(AddressTxUtxoObject$`timestamp`)) {
        self$`timestamp` <- AddressTxUtxoObject$`timestamp`
      }
      if (!is.null(AddressTxUtxoObject$`tx_hash`)) {
        self$`tx_hash` <- AddressTxUtxoObject$`tx_hash`
      }
      if (!is.null(AddressTxUtxoObject$`value`)) {
        valueObject <- Values$new()
        valueObject$fromJSON(jsonlite::toJSON(AddressTxUtxoObject$value, auto_unbox = TRUE, digits = NA))
        self$`value` <- valueObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`currency_type`)) {
        sprintf(
        '"currency_type":
          "%s"
                ',
        self$`currency_type`
        )},
        if (!is.null(self$`height`)) {
        sprintf(
        '"height":
          %d
                ',
        self$`height`
        )},
        if (!is.null(self$`timestamp`)) {
        sprintf(
        '"timestamp":
          %d
                ',
        self$`timestamp`
        )},
        if (!is.null(self$`tx_hash`)) {
        sprintf(
        '"tx_hash":
          "%s"
                ',
        self$`tx_hash`
        )},
        if (!is.null(self$`value`)) {
        sprintf(
        '"value":
        %s
        ',
        jsonlite::toJSON(self$`value`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(AddressTxUtxoJson) {
      AddressTxUtxoObject <- jsonlite::fromJSON(AddressTxUtxoJson)
      self$`currency_type` <- AddressTxUtxoObject$`currency_type`
      self$`height` <- AddressTxUtxoObject$`height`
      self$`timestamp` <- AddressTxUtxoObject$`timestamp`
      self$`tx_hash` <- AddressTxUtxoObject$`tx_hash`
      self$`value` <- Values$new()$fromJSON(jsonlite::toJSON(AddressTxUtxoObject$value, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)

