# GraphSense API
#
# GraphSense API
#
# The version of the OpenAPI document: 0.5
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title BatchOperation
#'
#' @description BatchOperation Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field api  character 
#'
#' @field operation  character 
#'
#' @field parameters  list( \link{ListEntityAddressesParameters} ) 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
BatchOperation <- R6::R6Class(
  'BatchOperation',
  public = list(
    `api` = NULL,
    `operation` = NULL,
    `parameters` = NULL,
    initialize = function(
        `api`, `operation`, `parameters`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`api`)) {
        stopifnot(is.character(`api`), length(`api`) == 1)
        self$`api` <- `api`
      }
      if (!missing(`operation`)) {
        stopifnot(is.character(`operation`), length(`operation`) == 1)
        self$`operation` <- `operation`
      }
      if (!missing(`parameters`)) {
        stopifnot(is.vector(`parameters`), length(`parameters`) != 0)
        sapply(`parameters`, function(x) stopifnot(R6::is.R6(x)))
        self$`parameters` <- `parameters`
      }
    },
    toJSON = function() {
      BatchOperationObject <- list()
      if (!is.null(self$`api`)) {
        BatchOperationObject[['api']] <-
          self$`api`
      }
      if (!is.null(self$`operation`)) {
        BatchOperationObject[['operation']] <-
          self$`operation`
      }
      if (!is.null(self$`parameters`)) {
        BatchOperationObject[['parameters']] <-
          lapply(self$`parameters`, function(x) x$toJSON())
      }

      BatchOperationObject
    },
    fromJSON = function(BatchOperationJson) {
      BatchOperationObject <- jsonlite::fromJSON(BatchOperationJson)
      if (!is.null(BatchOperationObject$`api`)) {
        self$`api` <- BatchOperationObject$`api`
      }
      if (!is.null(BatchOperationObject$`operation`)) {
        self$`operation` <- BatchOperationObject$`operation`
      }
      if (!is.null(BatchOperationObject$`parameters`)) {
        self$`parameters` <- ApiClient$new()$deserializeObj(BatchOperationObject$`parameters`, "array[ListEntityAddressesParameters]", loadNamespace("openapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`api`)) {
        sprintf(
        '"api":
          "%s"
                ',
        self$`api`
        )},
        if (!is.null(self$`operation`)) {
        sprintf(
        '"operation":
          "%s"
                ',
        self$`operation`
        )},
        if (!is.null(self$`parameters`)) {
        sprintf(
        '"parameters":
        [%s]
',
        paste(sapply(self$`parameters`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(BatchOperationJson) {
      BatchOperationObject <- jsonlite::fromJSON(BatchOperationJson)
      self$`api` <- BatchOperationObject$`api`
      self$`operation` <- BatchOperationObject$`operation`
      self$`parameters` <- ApiClient$new()$deserializeObj(BatchOperationObject$`parameters`, "array[ListEntityAddressesParameters]", loadNamespace("openapi"))
      self
    }
  )
)

