# GraphSense API
#
# GraphSense API
#
# The version of the OpenAPI document: 0.5
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title BatchResponse
#'
#' @description BatchResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field operation  character 
#'
#' @field result  list( \link{GetTxIoResult} ) 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
BatchResponse <- R6::R6Class(
  'BatchResponse',
  public = list(
    `operation` = NULL,
    `result` = NULL,
    initialize = function(
        `operation`, `result`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`operation`)) {
        stopifnot(is.character(`operation`), length(`operation`) == 1)
        self$`operation` <- `operation`
      }
      if (!missing(`result`)) {
        stopifnot(is.vector(`result`), length(`result`) != 0)
        sapply(`result`, function(x) stopifnot(R6::is.R6(x)))
        self$`result` <- `result`
      }
    },
    toJSON = function() {
      BatchResponseObject <- list()
      if (!is.null(self$`operation`)) {
        BatchResponseObject[['operation']] <-
          self$`operation`
      }
      if (!is.null(self$`result`)) {
        BatchResponseObject[['result']] <-
          lapply(self$`result`, function(x) x$toJSON())
      }

      BatchResponseObject
    },
    fromJSON = function(BatchResponseJson) {
      BatchResponseObject <- jsonlite::fromJSON(BatchResponseJson)
      if (!is.null(BatchResponseObject$`operation`)) {
        self$`operation` <- BatchResponseObject$`operation`
      }
      if (!is.null(BatchResponseObject$`result`)) {
        self$`result` <- ApiClient$new()$deserializeObj(BatchResponseObject$`result`, "array[GetTxIoResult]", loadNamespace("openapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`operation`)) {
        sprintf(
        '"operation":
          "%s"
                ',
        self$`operation`
        )},
        if (!is.null(self$`result`)) {
        sprintf(
        '"result":
        [%s]
',
        paste(sapply(self$`result`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(BatchResponseJson) {
      BatchResponseObject <- jsonlite::fromJSON(BatchResponseJson)
      self$`operation` <- BatchResponseObject$`operation`
      self$`result` <- ApiClient$new()$deserializeObj(BatchResponseObject$`result`, "array[GetTxIoResult]", loadNamespace("openapi"))
      self
    }
  )
)

