# GraphSense API
#
# GraphSense API
#
# The version of the OpenAPI document: 0.5
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title BlockTxUtxo
#'
#' @description BlockTxUtxo Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field currency_type  character 
#'
#' @field tx_hash  character 
#'
#' @field no_inputs  integer 
#'
#' @field no_outputs  integer 
#'
#' @field total_input  \link{Values} 
#'
#' @field total_output  \link{Values} 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
BlockTxUtxo <- R6::R6Class(
  'BlockTxUtxo',
  public = list(
    `currency_type` = NULL,
    `tx_hash` = NULL,
    `no_inputs` = NULL,
    `no_outputs` = NULL,
    `total_input` = NULL,
    `total_output` = NULL,
    initialize = function(
        `currency_type`, `tx_hash`, `no_inputs`, `no_outputs`, `total_input`, `total_output`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`currency_type`)) {
        stopifnot(is.character(`currency_type`), length(`currency_type`) == 1)
        self$`currency_type` <- `currency_type`
      }
      if (!missing(`tx_hash`)) {
        stopifnot(is.character(`tx_hash`), length(`tx_hash`) == 1)
        self$`tx_hash` <- `tx_hash`
      }
      if (!missing(`no_inputs`)) {
        stopifnot(is.numeric(`no_inputs`), length(`no_inputs`) == 1)
        self$`no_inputs` <- `no_inputs`
      }
      if (!missing(`no_outputs`)) {
        stopifnot(is.numeric(`no_outputs`), length(`no_outputs`) == 1)
        self$`no_outputs` <- `no_outputs`
      }
      if (!missing(`total_input`)) {
        stopifnot(R6::is.R6(`total_input`))
        self$`total_input` <- `total_input`
      }
      if (!missing(`total_output`)) {
        stopifnot(R6::is.R6(`total_output`))
        self$`total_output` <- `total_output`
      }
    },
    toJSON = function() {
      BlockTxUtxoObject <- list()
      if (!is.null(self$`currency_type`)) {
        BlockTxUtxoObject[['currency_type']] <-
          self$`currency_type`
      }
      if (!is.null(self$`tx_hash`)) {
        BlockTxUtxoObject[['tx_hash']] <-
          self$`tx_hash`
      }
      if (!is.null(self$`no_inputs`)) {
        BlockTxUtxoObject[['no_inputs']] <-
          self$`no_inputs`
      }
      if (!is.null(self$`no_outputs`)) {
        BlockTxUtxoObject[['no_outputs']] <-
          self$`no_outputs`
      }
      if (!is.null(self$`total_input`)) {
        BlockTxUtxoObject[['total_input']] <-
          self$`total_input`$toJSON()
      }
      if (!is.null(self$`total_output`)) {
        BlockTxUtxoObject[['total_output']] <-
          self$`total_output`$toJSON()
      }

      BlockTxUtxoObject
    },
    fromJSON = function(BlockTxUtxoJson) {
      BlockTxUtxoObject <- jsonlite::fromJSON(BlockTxUtxoJson)
      if (!is.null(BlockTxUtxoObject$`currency_type`)) {
        self$`currency_type` <- BlockTxUtxoObject$`currency_type`
      }
      if (!is.null(BlockTxUtxoObject$`tx_hash`)) {
        self$`tx_hash` <- BlockTxUtxoObject$`tx_hash`
      }
      if (!is.null(BlockTxUtxoObject$`no_inputs`)) {
        self$`no_inputs` <- BlockTxUtxoObject$`no_inputs`
      }
      if (!is.null(BlockTxUtxoObject$`no_outputs`)) {
        self$`no_outputs` <- BlockTxUtxoObject$`no_outputs`
      }
      if (!is.null(BlockTxUtxoObject$`total_input`)) {
        total_inputObject <- Values$new()
        total_inputObject$fromJSON(jsonlite::toJSON(BlockTxUtxoObject$total_input, auto_unbox = TRUE, digits = NA))
        self$`total_input` <- total_inputObject
      }
      if (!is.null(BlockTxUtxoObject$`total_output`)) {
        total_outputObject <- Values$new()
        total_outputObject$fromJSON(jsonlite::toJSON(BlockTxUtxoObject$total_output, auto_unbox = TRUE, digits = NA))
        self$`total_output` <- total_outputObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`currency_type`)) {
        sprintf(
        '"currency_type":
          "%s"
                ',
        self$`currency_type`
        )},
        if (!is.null(self$`tx_hash`)) {
        sprintf(
        '"tx_hash":
          "%s"
                ',
        self$`tx_hash`
        )},
        if (!is.null(self$`no_inputs`)) {
        sprintf(
        '"no_inputs":
          %d
                ',
        self$`no_inputs`
        )},
        if (!is.null(self$`no_outputs`)) {
        sprintf(
        '"no_outputs":
          %d
                ',
        self$`no_outputs`
        )},
        if (!is.null(self$`total_input`)) {
        sprintf(
        '"total_input":
        %s
        ',
        jsonlite::toJSON(self$`total_input`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`total_output`)) {
        sprintf(
        '"total_output":
        %s
        ',
        jsonlite::toJSON(self$`total_output`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(BlockTxUtxoJson) {
      BlockTxUtxoObject <- jsonlite::fromJSON(BlockTxUtxoJson)
      self$`currency_type` <- BlockTxUtxoObject$`currency_type`
      self$`tx_hash` <- BlockTxUtxoObject$`tx_hash`
      self$`no_inputs` <- BlockTxUtxoObject$`no_inputs`
      self$`no_outputs` <- BlockTxUtxoObject$`no_outputs`
      self$`total_input` <- Values$new()$fromJSON(jsonlite::toJSON(BlockTxUtxoObject$total_input, auto_unbox = TRUE, digits = NA))
      self$`total_output` <- Values$new()$fromJSON(jsonlite::toJSON(BlockTxUtxoObject$total_output, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)

