# GraphSense API
#
# GraphSense API
#
# The version of the OpenAPI document: 0.5
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title BlockTx
#'
#' @description BlockTx Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field currency_type  character 
#'
#' @field no_inputs  integer 
#'
#' @field no_outputs  integer 
#'
#' @field total_input  \link{Values} 
#'
#' @field total_output  \link{Values} 
#'
#' @field tx_hash  character 
#'
#' @field height  integer 
#'
#' @field timestamp  integer 
#'
#' @field values  \link{Values} 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
BlockTx <- R6::R6Class(
  'BlockTx',
  public = list(
    `currency_type` = NULL,
    `no_inputs` = NULL,
    `no_outputs` = NULL,
    `total_input` = NULL,
    `total_output` = NULL,
    `tx_hash` = NULL,
    `height` = NULL,
    `timestamp` = NULL,
    `values` = NULL,
    initialize = function(
        `currency_type`, `no_inputs`, `no_outputs`, `total_input`, `total_output`, `tx_hash`, `height`, `timestamp`, `values`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`currency_type`)) {
        stopifnot(is.character(`currency_type`), length(`currency_type`) == 1)
        self$`currency_type` <- `currency_type`
      }
      if (!missing(`no_inputs`)) {
        stopifnot(is.numeric(`no_inputs`), length(`no_inputs`) == 1)
        self$`no_inputs` <- `no_inputs`
      }
      if (!missing(`no_outputs`)) {
        stopifnot(is.numeric(`no_outputs`), length(`no_outputs`) == 1)
        self$`no_outputs` <- `no_outputs`
      }
      if (!missing(`total_input`)) {
        stopifnot(R6::is.R6(`total_input`))
        self$`total_input` <- `total_input`
      }
      if (!missing(`total_output`)) {
        stopifnot(R6::is.R6(`total_output`))
        self$`total_output` <- `total_output`
      }
      if (!missing(`tx_hash`)) {
        stopifnot(is.character(`tx_hash`), length(`tx_hash`) == 1)
        self$`tx_hash` <- `tx_hash`
      }
      if (!missing(`height`)) {
        stopifnot(is.numeric(`height`), length(`height`) == 1)
        self$`height` <- `height`
      }
      if (!missing(`timestamp`)) {
        stopifnot(is.numeric(`timestamp`), length(`timestamp`) == 1)
        self$`timestamp` <- `timestamp`
      }
      if (!missing(`values`)) {
        stopifnot(R6::is.R6(`values`))
        self$`values` <- `values`
      }
    },
    toJSON = function() {
      BlockTxObject <- list()
      if (!is.null(self$`currency_type`)) {
        BlockTxObject[['currency_type']] <-
          self$`currency_type`
      }
      if (!is.null(self$`no_inputs`)) {
        BlockTxObject[['no_inputs']] <-
          self$`no_inputs`
      }
      if (!is.null(self$`no_outputs`)) {
        BlockTxObject[['no_outputs']] <-
          self$`no_outputs`
      }
      if (!is.null(self$`total_input`)) {
        BlockTxObject[['total_input']] <-
          self$`total_input`$toJSON()
      }
      if (!is.null(self$`total_output`)) {
        BlockTxObject[['total_output']] <-
          self$`total_output`$toJSON()
      }
      if (!is.null(self$`tx_hash`)) {
        BlockTxObject[['tx_hash']] <-
          self$`tx_hash`
      }
      if (!is.null(self$`height`)) {
        BlockTxObject[['height']] <-
          self$`height`
      }
      if (!is.null(self$`timestamp`)) {
        BlockTxObject[['timestamp']] <-
          self$`timestamp`
      }
      if (!is.null(self$`values`)) {
        BlockTxObject[['values']] <-
          self$`values`$toJSON()
      }

      BlockTxObject
    },
    fromJSON = function(BlockTxJson) {
      BlockTxObject <- jsonlite::fromJSON(BlockTxJson)
      if (!is.null(BlockTxObject$`currency_type`)) {
        self$`currency_type` <- BlockTxObject$`currency_type`
      }
      if (!is.null(BlockTxObject$`no_inputs`)) {
        self$`no_inputs` <- BlockTxObject$`no_inputs`
      }
      if (!is.null(BlockTxObject$`no_outputs`)) {
        self$`no_outputs` <- BlockTxObject$`no_outputs`
      }
      if (!is.null(BlockTxObject$`total_input`)) {
        total_inputObject <- Values$new()
        total_inputObject$fromJSON(jsonlite::toJSON(BlockTxObject$total_input, auto_unbox = TRUE, digits = NA))
        self$`total_input` <- total_inputObject
      }
      if (!is.null(BlockTxObject$`total_output`)) {
        total_outputObject <- Values$new()
        total_outputObject$fromJSON(jsonlite::toJSON(BlockTxObject$total_output, auto_unbox = TRUE, digits = NA))
        self$`total_output` <- total_outputObject
      }
      if (!is.null(BlockTxObject$`tx_hash`)) {
        self$`tx_hash` <- BlockTxObject$`tx_hash`
      }
      if (!is.null(BlockTxObject$`height`)) {
        self$`height` <- BlockTxObject$`height`
      }
      if (!is.null(BlockTxObject$`timestamp`)) {
        self$`timestamp` <- BlockTxObject$`timestamp`
      }
      if (!is.null(BlockTxObject$`values`)) {
        valuesObject <- Values$new()
        valuesObject$fromJSON(jsonlite::toJSON(BlockTxObject$values, auto_unbox = TRUE, digits = NA))
        self$`values` <- valuesObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`currency_type`)) {
        sprintf(
        '"currency_type":
          "%s"
                ',
        self$`currency_type`
        )},
        if (!is.null(self$`no_inputs`)) {
        sprintf(
        '"no_inputs":
          %d
                ',
        self$`no_inputs`
        )},
        if (!is.null(self$`no_outputs`)) {
        sprintf(
        '"no_outputs":
          %d
                ',
        self$`no_outputs`
        )},
        if (!is.null(self$`total_input`)) {
        sprintf(
        '"total_input":
        %s
        ',
        jsonlite::toJSON(self$`total_input`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`total_output`)) {
        sprintf(
        '"total_output":
        %s
        ',
        jsonlite::toJSON(self$`total_output`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`tx_hash`)) {
        sprintf(
        '"tx_hash":
          "%s"
                ',
        self$`tx_hash`
        )},
        if (!is.null(self$`height`)) {
        sprintf(
        '"height":
          %d
                ',
        self$`height`
        )},
        if (!is.null(self$`timestamp`)) {
        sprintf(
        '"timestamp":
          %d
                ',
        self$`timestamp`
        )},
        if (!is.null(self$`values`)) {
        sprintf(
        '"values":
        %s
        ',
        jsonlite::toJSON(self$`values`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(BlockTxJson) {
      BlockTxObject <- jsonlite::fromJSON(BlockTxJson)
      self$`currency_type` <- BlockTxObject$`currency_type`
      self$`no_inputs` <- BlockTxObject$`no_inputs`
      self$`no_outputs` <- BlockTxObject$`no_outputs`
      self$`total_input` <- Values$new()$fromJSON(jsonlite::toJSON(BlockTxObject$total_input, auto_unbox = TRUE, digits = NA))
      self$`total_output` <- Values$new()$fromJSON(jsonlite::toJSON(BlockTxObject$total_output, auto_unbox = TRUE, digits = NA))
      self$`tx_hash` <- BlockTxObject$`tx_hash`
      self$`height` <- BlockTxObject$`height`
      self$`timestamp` <- BlockTxObject$`timestamp`
      self$`values` <- Values$new()$fromJSON(jsonlite::toJSON(BlockTxObject$values, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)

