# GraphSense API
#
# GraphSense API
#
# The version of the OpenAPI document: 0.5.1-dev
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title CurrencyStats
#'
#' @description CurrencyStats Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field name  character [optional]
#'
#' @field no_address_relations  integer [optional]
#'
#' @field no_addresses  integer [optional]
#'
#' @field no_blocks  integer [optional]
#'
#' @field no_entities  integer [optional]
#'
#' @field no_labels  integer [optional]
#'
#' @field no_txs  integer [optional]
#'
#' @field timestamp  integer [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CurrencyStats <- R6::R6Class(
  'CurrencyStats',
  public = list(
    `name` = NULL,
    `no_address_relations` = NULL,
    `no_addresses` = NULL,
    `no_blocks` = NULL,
    `no_entities` = NULL,
    `no_labels` = NULL,
    `no_txs` = NULL,
    `timestamp` = NULL,
    initialize = function(
        `name`=NULL, `no_address_relations`=NULL, `no_addresses`=NULL, `no_blocks`=NULL, `no_entities`=NULL, `no_labels`=NULL, `no_txs`=NULL, `timestamp`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`no_address_relations`)) {
        stopifnot(is.numeric(`no_address_relations`), length(`no_address_relations`) == 1)
        self$`no_address_relations` <- `no_address_relations`
      }
      if (!is.null(`no_addresses`)) {
        stopifnot(is.numeric(`no_addresses`), length(`no_addresses`) == 1)
        self$`no_addresses` <- `no_addresses`
      }
      if (!is.null(`no_blocks`)) {
        stopifnot(is.numeric(`no_blocks`), length(`no_blocks`) == 1)
        self$`no_blocks` <- `no_blocks`
      }
      if (!is.null(`no_entities`)) {
        stopifnot(is.numeric(`no_entities`), length(`no_entities`) == 1)
        self$`no_entities` <- `no_entities`
      }
      if (!is.null(`no_labels`)) {
        stopifnot(is.numeric(`no_labels`), length(`no_labels`) == 1)
        self$`no_labels` <- `no_labels`
      }
      if (!is.null(`no_txs`)) {
        stopifnot(is.numeric(`no_txs`), length(`no_txs`) == 1)
        self$`no_txs` <- `no_txs`
      }
      if (!is.null(`timestamp`)) {
        stopifnot(is.numeric(`timestamp`), length(`timestamp`) == 1)
        self$`timestamp` <- `timestamp`
      }
    },
    toJSON = function() {
      CurrencyStatsObject <- list()
      if (!is.null(self$`name`)) {
        CurrencyStatsObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`no_address_relations`)) {
        CurrencyStatsObject[['no_address_relations']] <-
          self$`no_address_relations`
      }
      if (!is.null(self$`no_addresses`)) {
        CurrencyStatsObject[['no_addresses']] <-
          self$`no_addresses`
      }
      if (!is.null(self$`no_blocks`)) {
        CurrencyStatsObject[['no_blocks']] <-
          self$`no_blocks`
      }
      if (!is.null(self$`no_entities`)) {
        CurrencyStatsObject[['no_entities']] <-
          self$`no_entities`
      }
      if (!is.null(self$`no_labels`)) {
        CurrencyStatsObject[['no_labels']] <-
          self$`no_labels`
      }
      if (!is.null(self$`no_txs`)) {
        CurrencyStatsObject[['no_txs']] <-
          self$`no_txs`
      }
      if (!is.null(self$`timestamp`)) {
        CurrencyStatsObject[['timestamp']] <-
          self$`timestamp`
      }

      CurrencyStatsObject
    },
    fromJSON = function(CurrencyStatsJson) {
      CurrencyStatsObject <- jsonlite::fromJSON(CurrencyStatsJson)
      if (!is.null(CurrencyStatsObject$`name`)) {
        self$`name` <- CurrencyStatsObject$`name`
      }
      if (!is.null(CurrencyStatsObject$`no_address_relations`)) {
        self$`no_address_relations` <- CurrencyStatsObject$`no_address_relations`
      }
      if (!is.null(CurrencyStatsObject$`no_addresses`)) {
        self$`no_addresses` <- CurrencyStatsObject$`no_addresses`
      }
      if (!is.null(CurrencyStatsObject$`no_blocks`)) {
        self$`no_blocks` <- CurrencyStatsObject$`no_blocks`
      }
      if (!is.null(CurrencyStatsObject$`no_entities`)) {
        self$`no_entities` <- CurrencyStatsObject$`no_entities`
      }
      if (!is.null(CurrencyStatsObject$`no_labels`)) {
        self$`no_labels` <- CurrencyStatsObject$`no_labels`
      }
      if (!is.null(CurrencyStatsObject$`no_txs`)) {
        self$`no_txs` <- CurrencyStatsObject$`no_txs`
      }
      if (!is.null(CurrencyStatsObject$`timestamp`)) {
        self$`timestamp` <- CurrencyStatsObject$`timestamp`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`no_address_relations`)) {
        sprintf(
        '"no_address_relations":
          %d
                ',
        self$`no_address_relations`
        )},
        if (!is.null(self$`no_addresses`)) {
        sprintf(
        '"no_addresses":
          %d
                ',
        self$`no_addresses`
        )},
        if (!is.null(self$`no_blocks`)) {
        sprintf(
        '"no_blocks":
          %d
                ',
        self$`no_blocks`
        )},
        if (!is.null(self$`no_entities`)) {
        sprintf(
        '"no_entities":
          %d
                ',
        self$`no_entities`
        )},
        if (!is.null(self$`no_labels`)) {
        sprintf(
        '"no_labels":
          %d
                ',
        self$`no_labels`
        )},
        if (!is.null(self$`no_txs`)) {
        sprintf(
        '"no_txs":
          %d
                ',
        self$`no_txs`
        )},
        if (!is.null(self$`timestamp`)) {
        sprintf(
        '"timestamp":
          %d
                ',
        self$`timestamp`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(CurrencyStatsJson) {
      CurrencyStatsObject <- jsonlite::fromJSON(CurrencyStatsJson)
      self$`name` <- CurrencyStatsObject$`name`
      self$`no_address_relations` <- CurrencyStatsObject$`no_address_relations`
      self$`no_addresses` <- CurrencyStatsObject$`no_addresses`
      self$`no_blocks` <- CurrencyStatsObject$`no_blocks`
      self$`no_entities` <- CurrencyStatsObject$`no_entities`
      self$`no_labels` <- CurrencyStatsObject$`no_labels`
      self$`no_txs` <- CurrencyStatsObject$`no_txs`
      self$`timestamp` <- CurrencyStatsObject$`timestamp`
      self
    }
  )
)

