# GraphSense API
#
# GraphSense API
#
# The version of the OpenAPI document: 0.5
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title EntityTagAllOf
#'
#' @description EntityTagAllOf Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field entity  integer 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EntityTagAllOf <- R6::R6Class(
  'EntityTagAllOf',
  public = list(
    `entity` = NULL,
    initialize = function(
        `entity`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`entity`)) {
        stopifnot(is.numeric(`entity`), length(`entity`) == 1)
        self$`entity` <- `entity`
      }
    },
    toJSON = function() {
      EntityTagAllOfObject <- list()
      if (!is.null(self$`entity`)) {
        EntityTagAllOfObject[['entity']] <-
          self$`entity`
      }

      EntityTagAllOfObject
    },
    fromJSON = function(EntityTagAllOfJson) {
      EntityTagAllOfObject <- jsonlite::fromJSON(EntityTagAllOfJson)
      if (!is.null(EntityTagAllOfObject$`entity`)) {
        self$`entity` <- EntityTagAllOfObject$`entity`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`entity`)) {
        sprintf(
        '"entity":
          %d
                ',
        self$`entity`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(EntityTagAllOfJson) {
      EntityTagAllOfObject <- jsonlite::fromJSON(EntityTagAllOfJson)
      self$`entity` <- EntityTagAllOfObject$`entity`
      self
    }
  )
)

