# GraphSense API
#
# GraphSense API
#
# The version of the OpenAPI document: 0.5
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Entities operations
#' @description openapi.Entities
#' @format An \code{R6Class} generator object
#' @field apiClient Handles the client-server communication.
#'
#' @section Methods:
#' \describe{
#' \strong{ GetEntity } \emph{ Get an entity, optionally with tags }
#' 
#'
#' \itemize{
#' \item \emph{ @param } currency character
#' \item \emph{ @param } entity integer
#' \item \emph{ @param } include.tags character
#' \item \emph{ @param } tag.coherence character
#' \item \emph{ @returnType } \link{Entity} \cr
#'
#'
#' \item status code : 200 | OK
#'
#' \item return type : Entity 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ListEntities } \emph{ Get entities }
#' 
#'
#' \itemize{
#' \item \emph{ @param } currency character
#' \item \emph{ @param } ids list( integer )
#' \item \emph{ @param } page character
#' \item \emph{ @param } pagesize integer
#' \item \emph{ @returnType } \link{Entities} \cr
#'
#'
#' \item status code : 200 | OK
#'
#' \item return type : Entities 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ListEntitiesCsv } \emph{ Get entities as CSV }
#' 
#'
#' \itemize{
#' \item \emph{ @param } currency character
#' \item \emph{ @param } ids list( integer )
#'
#'
#' \item status code : 200 | OK
#'
#' \item return type : character 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ListEntityAddresses } \emph{ Get an entity&#39;s addresses }
#' 
#'
#' \itemize{
#' \item \emph{ @param } currency character
#' \item \emph{ @param } entity integer
#' \item \emph{ @param } page character
#' \item \emph{ @param } pagesize integer
#' \item \emph{ @returnType } \link{EntityAddresses} \cr
#'
#'
#' \item status code : 200 | OK
#'
#' \item return type : EntityAddresses 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ListEntityAddressesCsv } \emph{ Get an entity&#39;s addresses as CSV }
#' 
#'
#' \itemize{
#' \item \emph{ @param } currency character
#' \item \emph{ @param } entity integer
#'
#'
#' \item status code : 200 | OK
#'
#' \item return type : character 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ListEntityLinks } \emph{ Get transactions between two entities }
#' 
#'
#' \itemize{
#' \item \emph{ @param } currency character
#' \item \emph{ @param } entity integer
#' \item \emph{ @param } neighbor integer
#' \item \emph{ @returnType } \link{Links} \cr
#'
#'
#' \item status code : 200 | OK
#'
#' \item return type : Links 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ListEntityLinksCsv } \emph{ Get transactions between two entities as CSV }
#' 
#'
#' \itemize{
#' \item \emph{ @param } currency character
#' \item \emph{ @param } entity integer
#' \item \emph{ @param } neighbor integer
#'
#'
#' \item status code : 200 | OK
#'
#' \item return type : character 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ListEntityNeighbors } \emph{ Get an entity&#39;s neighbors in the entity graph }
#' 
#'
#' \itemize{
#' \item \emph{ @param } currency character
#' \item \emph{ @param } entity integer
#' \item \emph{ @param } direction Enum < [in, out] > 
#' \item \emph{ @param } ids list( integer )
#' \item \emph{ @param } include.labels character
#' \item \emph{ @param } page character
#' \item \emph{ @param } pagesize integer
#' \item \emph{ @returnType } \link{Neighbors} \cr
#'
#'
#' \item status code : 200 | OK
#'
#' \item return type : Neighbors 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ListEntityNeighborsCsv } \emph{ Get an entity&#39;s neighbors in the entity graph as CSV }
#' 
#'
#' \itemize{
#' \item \emph{ @param } currency character
#' \item \emph{ @param } entity integer
#' \item \emph{ @param } direction Enum < [in, out] > 
#' \item \emph{ @param } include.labels character
#'
#'
#' \item status code : 200 | OK
#'
#' \item return type : character 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ListEntityTxs } \emph{ Get all transactions an entity has been involved in }
#' 
#'
#' \itemize{
#' \item \emph{ @param } currency character
#' \item \emph{ @param } entity integer
#' \item \emph{ @param } page character
#' \item \emph{ @param } pagesize integer
#' \item \emph{ @returnType } \link{TxsAccount} \cr
#'
#'
#' \item status code : 200 | OK
#'
#' \item return type : TxsAccount 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ListEntityTxsCsv } \emph{ Get all transactions an entity has been involved in as CSV }
#' 
#'
#' \itemize{
#' \item \emph{ @param } currency character
#' \item \emph{ @param } entity integer
#'
#'
#' \item status code : 200 | OK
#'
#' \item return type : character 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ListTagsByEntity } \emph{ Get tags for a given entity }
#' 
#'
#' \itemize{
#' \item \emph{ @param } currency character
#' \item \emph{ @param } entity integer
#' \item \emph{ @param } tag.coherence character
#' \item \emph{ @returnType } \link{Tags} \cr
#'
#'
#' \item status code : 200 | OK
#'
#' \item return type : Tags 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ListTagsByEntityByLevelCsv } \emph{ Get address or entity tags for a given entity as CSV }
#' 
#'
#' \itemize{
#' \item \emph{ @param } currency character
#' \item \emph{ @param } entity integer
#' \item \emph{ @param } level Enum < [address, entity] > 
#'
#'
#' \item status code : 200 | OK
#'
#' \item return type : character 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ SearchEntityNeighbors } \emph{ Search deeply for matching neighbors }
#' 
#'
#' \itemize{
#' \item \emph{ @param } currency character
#' \item \emph{ @param } entity integer
#' \item \emph{ @param } direction Enum < [in, out] > 
#' \item \emph{ @param } key Enum < [category, addresses, entities, total_received, balance] > 
#' \item \emph{ @param } value list( character )
#' \item \emph{ @param } depth integer
#' \item \emph{ @param } breadth integer
#' \item \emph{ @param } skip.num.addresses integer
#' \item \emph{ @returnType } list( \link{search_result_level1} ) \cr
#'
#'
#' \item status code : 200 | OK
#'
#' \item return type : array[SearchResultLevel1] 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' }
#'
#'
#' @examples
#' \dontrun{
#' ####################  GetEntity  ####################
#'
#' library(openapi)
#' var.currency <- 'btc' # character | The cryptocurrency (e.g., btc)
#' var.entity <- 67065 # integer | The entity ID
#' var.include.tags <- FALSE # character | Whether tags should be included
#' var.tag.coherence <- FALSE # character | Whether to calculate coherence of address tags
#'
#' #Get an entity, optionally with tags
#' api.instance <- EntitiesApi$new()
#'
#' result <- api.instance$GetEntity(var.currency, var.entity, include.tags=var.include.tags, tag.coherence=var.tag.coherence)
#'
#'
#' ####################  ListEntities  ####################
#'
#' library(openapi)
#' var.currency <- 'btc' # character | The cryptocurrency (e.g., btc)
#' var.ids <- [56] # array[integer] | Restrict result to given set of comma separated IDs
#' var.page <- 'page_example' # character | Resumption token for retrieving the next page
#' var.pagesize <- 10 # integer | Number of items returned in a single page
#'
#' #Get entities
#' api.instance <- EntitiesApi$new()
#'
#' result <- api.instance$ListEntities(var.currency, ids=var.ids, page=var.page, pagesize=var.pagesize)
#'
#'
#' ####################  ListEntitiesCsv  ####################
#'
#' library(openapi)
#' var.currency <- 'btc' # character | The cryptocurrency (e.g., btc)
#' var.ids <- [56] # array[integer] | Set of comma separated IDs
#'
#' #Get entities as CSV
#' api.instance <- EntitiesApi$new()
#'
#' result <- api.instance$ListEntitiesCsv(var.currency, var.ids)
#'
#'
#' ####################  ListEntityAddresses  ####################
#'
#' library(openapi)
#' var.currency <- 'btc' # character | The cryptocurrency (e.g., btc)
#' var.entity <- 67065 # integer | The entity ID
#' var.page <- 'page_example' # character | Resumption token for retrieving the next page
#' var.pagesize <- 10 # integer | Number of items returned in a single page
#'
#' #Get an entity's addresses
#' api.instance <- EntitiesApi$new()
#'
#' result <- api.instance$ListEntityAddresses(var.currency, var.entity, page=var.page, pagesize=var.pagesize)
#'
#'
#' ####################  ListEntityAddressesCsv  ####################
#'
#' library(openapi)
#' var.currency <- 'btc' # character | The cryptocurrency (e.g., btc)
#' var.entity <- 67065 # integer | The entity ID
#'
#' #Get an entity's addresses as CSV
#' api.instance <- EntitiesApi$new()
#'
#' result <- api.instance$ListEntityAddressesCsv(var.currency, var.entity)
#'
#'
#' ####################  ListEntityLinks  ####################
#'
#' library(openapi)
#' var.currency <- 'btc' # character | The cryptocurrency (e.g., btc)
#' var.entity <- 67065 # integer | The entity ID
#' var.neighbor <- 123456 # integer | Neighbor entity
#'
#' #Get transactions between two entities
#' api.instance <- EntitiesApi$new()
#'
#' result <- api.instance$ListEntityLinks(var.currency, var.entity, var.neighbor)
#'
#'
#' ####################  ListEntityLinksCsv  ####################
#'
#' library(openapi)
#' var.currency <- 'btc' # character | The cryptocurrency (e.g., btc)
#' var.entity <- 67065 # integer | The entity ID
#' var.neighbor <- 123456 # integer | Neighbor entity
#'
#' #Get transactions between two entities as CSV
#' api.instance <- EntitiesApi$new()
#'
#' result <- api.instance$ListEntityLinksCsv(var.currency, var.entity, var.neighbor)
#'
#'
#' ####################  ListEntityNeighbors  ####################
#'
#' library(openapi)
#' var.currency <- 'btc' # character | The cryptocurrency (e.g., btc)
#' var.entity <- 67065 # integer | The entity ID
#' var.direction <- 'out' # character | Incoming or outgoing neighbors
#' var.ids <- [56] # array[integer] | Restrict result to given set of comma separated IDs
#' var.include.labels <- FALSE # character | Whether labels of tags should be included
#' var.page <- 'page_example' # character | Resumption token for retrieving the next page
#' var.pagesize <- 10 # integer | Number of items returned in a single page
#'
#' #Get an entity's neighbors in the entity graph
#' api.instance <- EntitiesApi$new()
#'
#' result <- api.instance$ListEntityNeighbors(var.currency, var.entity, var.direction, ids=var.ids, include.labels=var.include.labels, page=var.page, pagesize=var.pagesize)
#'
#'
#' ####################  ListEntityNeighborsCsv  ####################
#'
#' library(openapi)
#' var.currency <- 'btc' # character | The cryptocurrency (e.g., btc)
#' var.entity <- 67065 # integer | The entity ID
#' var.direction <- 'out' # character | Incoming or outgoing neighbors
#' var.include.labels <- FALSE # character | Whether labels of tags should be included
#'
#' #Get an entity's neighbors in the entity graph as CSV
#' api.instance <- EntitiesApi$new()
#'
#' result <- api.instance$ListEntityNeighborsCsv(var.currency, var.entity, var.direction, include.labels=var.include.labels)
#'
#'
#' ####################  ListEntityTxs  ####################
#'
#' library(openapi)
#' var.currency <- 'btc' # character | The cryptocurrency (e.g., btc)
#' var.entity <- 67065 # integer | The entity ID
#' var.page <- 'page_example' # character | Resumption token for retrieving the next page
#' var.pagesize <- 10 # integer | Number of items returned in a single page
#'
#' #Get all transactions an entity has been involved in
#' api.instance <- EntitiesApi$new()
#'
#' result <- api.instance$ListEntityTxs(var.currency, var.entity, page=var.page, pagesize=var.pagesize)
#'
#'
#' ####################  ListEntityTxsCsv  ####################
#'
#' library(openapi)
#' var.currency <- 'btc' # character | The cryptocurrency (e.g., btc)
#' var.entity <- 67065 # integer | The entity ID
#'
#' #Get all transactions an entity has been involved in as CSV
#' api.instance <- EntitiesApi$new()
#'
#' result <- api.instance$ListEntityTxsCsv(var.currency, var.entity)
#'
#'
#' ####################  ListTagsByEntity  ####################
#'
#' library(openapi)
#' var.currency <- 'btc' # character | The cryptocurrency (e.g., btc)
#' var.entity <- 67065 # integer | The entity ID
#' var.tag.coherence <- FALSE # character | Whether to calculate coherence of address tags
#'
#' #Get tags for a given entity
#' api.instance <- EntitiesApi$new()
#'
#' result <- api.instance$ListTagsByEntity(var.currency, var.entity, tag.coherence=var.tag.coherence)
#'
#'
#' ####################  ListTagsByEntityByLevelCsv  ####################
#'
#' library(openapi)
#' var.currency <- 'btc' # character | The cryptocurrency (e.g., btc)
#' var.entity <- 67065 # integer | The entity ID
#' var.level <- 'address' # character | Whether tags on the address or entity level are requested
#'
#' #Get address or entity tags for a given entity as CSV
#' api.instance <- EntitiesApi$new()
#'
#' result <- api.instance$ListTagsByEntityByLevelCsv(var.currency, var.entity, var.level)
#'
#'
#' ####################  SearchEntityNeighbors  ####################
#'
#' library(openapi)
#' var.currency <- 'btc' # character | The cryptocurrency (e.g., btc)
#' var.entity <- 67065 # integer | The entity ID
#' var.direction <- 'out' # character | Incoming or outgoing neighbors
#' var.key <- 'category' # character | Match neighbors against one and only one of these properties: - the category the entity belongs to - addresses the entity contains - entity ids - total_received: amount the entity received in total - balance: amount the entity holds finally
#' var.value <- ['Miner'] # array[character] | If key is - category: comma separated list of category names - addresses: comma separated list of address IDs - entities: comma separated list of entity IDs - total_received/balance: comma separated tuple of (currency, min, max) where currency is 'value' for the cryptocurrency value or an ISO currency code
#' var.depth <- 2 # integer | How many hops should the transaction graph be searched
#' var.breadth <- 16 # integer | How many siblings of each neighbor should be tried
#' var.skip.num.addresses <- 56 # integer | Skip entities containing more addresses
#'
#' #Search deeply for matching neighbors
#' api.instance <- EntitiesApi$new()
#'
#' result <- api.instance$SearchEntityNeighbors(var.currency, var.entity, var.direction, var.key, var.value, var.depth, breadth=var.breadth, skip.num.addresses=var.skip.num.addresses)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
EntitiesApi <- R6::R6Class(
  'EntitiesApi',
  public = list(
    apiClient = NULL,
    initialize = function(apiClient){
      if (!missing(apiClient)) {
        self$apiClient <- apiClient
      }
      else {
        self$apiClient <- ApiClient$new()
      }
    },
    GetEntity = function(currency, entity, include.tags=FALSE, tag.coherence=FALSE, ...){
      apiResponse <- self$GetEntityWithHttpInfo(currency, entity, include.tags, tag.coherence, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    GetEntityWithHttpInfo = function(currency, entity, include.tags=FALSE, tag.coherence=FALSE, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`currency`)) {
        stop("Missing required parameter `currency`.")
      }

      if (missing(`entity`)) {
        stop("Missing required parameter `entity`.")
      }

      queryParams['include_tags'] <- include.tags

      queryParams['tag_coherence'] <- tag.coherence

      body <- NULL
      urlPath <- "/{currency}/entities/{entity}"
      if (!missing(`currency`)) {
        urlPath <- gsub(paste0("\\{", "currency", "\\}"), URLencode(as.character(`currency`), reserved = TRUE), urlPath)
      }

      if (!missing(`entity`)) {
        urlPath <- gsub(paste0("\\{", "entity", "\\}"), URLencode(as.character(`entity`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "Entity", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ListEntities = function(currency, ids=NULL, page=NULL, pagesize=NULL, ...){
      apiResponse <- self$ListEntitiesWithHttpInfo(currency, ids, page, pagesize, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ListEntitiesWithHttpInfo = function(currency, ids=NULL, page=NULL, pagesize=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`currency`)) {
        stop("Missing required parameter `currency`.")
      }

      queryParams['ids'] <- ids

      queryParams['page'] <- page

      queryParams['pagesize'] <- pagesize

      body <- NULL
      urlPath <- "/{currency}/entities"
      if (!missing(`currency`)) {
        urlPath <- gsub(paste0("\\{", "currency", "\\}"), URLencode(as.character(`currency`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "Entities", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ListEntitiesCsv = function(currency, ids, ...){
      apiResponse <- self$ListEntitiesCsvWithHttpInfo(currency, ids, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ListEntitiesCsvWithHttpInfo = function(currency, ids, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`currency`)) {
        stop("Missing required parameter `currency`.")
      }

      if (missing(`ids`)) {
        stop("Missing required parameter `ids`.")
      }

      queryParams['ids'] <- ids

      body <- NULL
      urlPath <- "/{currency}/entities.csv"
      if (!missing(`currency`)) {
        urlPath <- gsub(paste0("\\{", "currency", "\\}"), URLencode(as.character(`currency`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "character", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ListEntityAddresses = function(currency, entity, page=NULL, pagesize=NULL, ...){
      apiResponse <- self$ListEntityAddressesWithHttpInfo(currency, entity, page, pagesize, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ListEntityAddressesWithHttpInfo = function(currency, entity, page=NULL, pagesize=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`currency`)) {
        stop("Missing required parameter `currency`.")
      }

      if (missing(`entity`)) {
        stop("Missing required parameter `entity`.")
      }

      queryParams['page'] <- page

      queryParams['pagesize'] <- pagesize

      body <- NULL
      urlPath <- "/{currency}/entities/{entity}/addresses"
      if (!missing(`currency`)) {
        urlPath <- gsub(paste0("\\{", "currency", "\\}"), URLencode(as.character(`currency`), reserved = TRUE), urlPath)
      }

      if (!missing(`entity`)) {
        urlPath <- gsub(paste0("\\{", "entity", "\\}"), URLencode(as.character(`entity`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "EntityAddresses", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ListEntityAddressesCsv = function(currency, entity, ...){
      apiResponse <- self$ListEntityAddressesCsvWithHttpInfo(currency, entity, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ListEntityAddressesCsvWithHttpInfo = function(currency, entity, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`currency`)) {
        stop("Missing required parameter `currency`.")
      }

      if (missing(`entity`)) {
        stop("Missing required parameter `entity`.")
      }

      body <- NULL
      urlPath <- "/{currency}/entities/{entity}/addresses.csv"
      if (!missing(`currency`)) {
        urlPath <- gsub(paste0("\\{", "currency", "\\}"), URLencode(as.character(`currency`), reserved = TRUE), urlPath)
      }

      if (!missing(`entity`)) {
        urlPath <- gsub(paste0("\\{", "entity", "\\}"), URLencode(as.character(`entity`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "character", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ListEntityLinks = function(currency, entity, neighbor, ...){
      apiResponse <- self$ListEntityLinksWithHttpInfo(currency, entity, neighbor, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ListEntityLinksWithHttpInfo = function(currency, entity, neighbor, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`currency`)) {
        stop("Missing required parameter `currency`.")
      }

      if (missing(`entity`)) {
        stop("Missing required parameter `entity`.")
      }

      if (missing(`neighbor`)) {
        stop("Missing required parameter `neighbor`.")
      }

      queryParams['neighbor'] <- neighbor

      body <- NULL
      urlPath <- "/{currency}/entities/{entity}/links"
      if (!missing(`currency`)) {
        urlPath <- gsub(paste0("\\{", "currency", "\\}"), URLencode(as.character(`currency`), reserved = TRUE), urlPath)
      }

      if (!missing(`entity`)) {
        urlPath <- gsub(paste0("\\{", "entity", "\\}"), URLencode(as.character(`entity`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "Links", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ListEntityLinksCsv = function(currency, entity, neighbor, ...){
      apiResponse <- self$ListEntityLinksCsvWithHttpInfo(currency, entity, neighbor, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ListEntityLinksCsvWithHttpInfo = function(currency, entity, neighbor, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`currency`)) {
        stop("Missing required parameter `currency`.")
      }

      if (missing(`entity`)) {
        stop("Missing required parameter `entity`.")
      }

      if (missing(`neighbor`)) {
        stop("Missing required parameter `neighbor`.")
      }

      queryParams['neighbor'] <- neighbor

      body <- NULL
      urlPath <- "/{currency}/entities/{entity}/links.csv"
      if (!missing(`currency`)) {
        urlPath <- gsub(paste0("\\{", "currency", "\\}"), URLencode(as.character(`currency`), reserved = TRUE), urlPath)
      }

      if (!missing(`entity`)) {
        urlPath <- gsub(paste0("\\{", "entity", "\\}"), URLencode(as.character(`entity`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "character", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ListEntityNeighbors = function(currency, entity, direction, ids=NULL, include.labels=FALSE, page=NULL, pagesize=NULL, ...){
      apiResponse <- self$ListEntityNeighborsWithHttpInfo(currency, entity, direction, ids, include.labels, page, pagesize, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ListEntityNeighborsWithHttpInfo = function(currency, entity, direction, ids=NULL, include.labels=FALSE, page=NULL, pagesize=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`currency`)) {
        stop("Missing required parameter `currency`.")
      }

      if (missing(`entity`)) {
        stop("Missing required parameter `entity`.")
      }

      if (missing(`direction`)) {
        stop("Missing required parameter `direction`.")
      }

      queryParams['direction'] <- direction

      queryParams['ids'] <- ids

      queryParams['include_labels'] <- include.labels

      queryParams['page'] <- page

      queryParams['pagesize'] <- pagesize

      body <- NULL
      urlPath <- "/{currency}/entities/{entity}/neighbors"
      if (!missing(`currency`)) {
        urlPath <- gsub(paste0("\\{", "currency", "\\}"), URLencode(as.character(`currency`), reserved = TRUE), urlPath)
      }

      if (!missing(`entity`)) {
        urlPath <- gsub(paste0("\\{", "entity", "\\}"), URLencode(as.character(`entity`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "Neighbors", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ListEntityNeighborsCsv = function(currency, entity, direction, include.labels=FALSE, ...){
      apiResponse <- self$ListEntityNeighborsCsvWithHttpInfo(currency, entity, direction, include.labels, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ListEntityNeighborsCsvWithHttpInfo = function(currency, entity, direction, include.labels=FALSE, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`currency`)) {
        stop("Missing required parameter `currency`.")
      }

      if (missing(`entity`)) {
        stop("Missing required parameter `entity`.")
      }

      if (missing(`direction`)) {
        stop("Missing required parameter `direction`.")
      }

      queryParams['direction'] <- direction

      queryParams['include_labels'] <- include.labels

      body <- NULL
      urlPath <- "/{currency}/entities/{entity}/neighbors.csv"
      if (!missing(`currency`)) {
        urlPath <- gsub(paste0("\\{", "currency", "\\}"), URLencode(as.character(`currency`), reserved = TRUE), urlPath)
      }

      if (!missing(`entity`)) {
        urlPath <- gsub(paste0("\\{", "entity", "\\}"), URLencode(as.character(`entity`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "character", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ListEntityTxs = function(currency, entity, page=NULL, pagesize=NULL, ...){
      apiResponse <- self$ListEntityTxsWithHttpInfo(currency, entity, page, pagesize, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ListEntityTxsWithHttpInfo = function(currency, entity, page=NULL, pagesize=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`currency`)) {
        stop("Missing required parameter `currency`.")
      }

      if (missing(`entity`)) {
        stop("Missing required parameter `entity`.")
      }

      queryParams['page'] <- page

      queryParams['pagesize'] <- pagesize

      body <- NULL
      urlPath <- "/{currency}/entities/{entity}/txs"
      if (!missing(`currency`)) {
        urlPath <- gsub(paste0("\\{", "currency", "\\}"), URLencode(as.character(`currency`), reserved = TRUE), urlPath)
      }

      if (!missing(`entity`)) {
        urlPath <- gsub(paste0("\\{", "entity", "\\}"), URLencode(as.character(`entity`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "TxsAccount", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ListEntityTxsCsv = function(currency, entity, ...){
      apiResponse <- self$ListEntityTxsCsvWithHttpInfo(currency, entity, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ListEntityTxsCsvWithHttpInfo = function(currency, entity, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`currency`)) {
        stop("Missing required parameter `currency`.")
      }

      if (missing(`entity`)) {
        stop("Missing required parameter `entity`.")
      }

      body <- NULL
      urlPath <- "/{currency}/entities/{entity}/txs.csv"
      if (!missing(`currency`)) {
        urlPath <- gsub(paste0("\\{", "currency", "\\}"), URLencode(as.character(`currency`), reserved = TRUE), urlPath)
      }

      if (!missing(`entity`)) {
        urlPath <- gsub(paste0("\\{", "entity", "\\}"), URLencode(as.character(`entity`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "character", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ListTagsByEntity = function(currency, entity, tag.coherence=FALSE, ...){
      apiResponse <- self$ListTagsByEntityWithHttpInfo(currency, entity, tag.coherence, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ListTagsByEntityWithHttpInfo = function(currency, entity, tag.coherence=FALSE, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`currency`)) {
        stop("Missing required parameter `currency`.")
      }

      if (missing(`entity`)) {
        stop("Missing required parameter `entity`.")
      }

      queryParams['tag_coherence'] <- tag.coherence

      body <- NULL
      urlPath <- "/{currency}/entities/{entity}/tags"
      if (!missing(`currency`)) {
        urlPath <- gsub(paste0("\\{", "currency", "\\}"), URLencode(as.character(`currency`), reserved = TRUE), urlPath)
      }

      if (!missing(`entity`)) {
        urlPath <- gsub(paste0("\\{", "entity", "\\}"), URLencode(as.character(`entity`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "Tags", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ListTagsByEntityByLevelCsv = function(currency, entity, level, ...){
      apiResponse <- self$ListTagsByEntityByLevelCsvWithHttpInfo(currency, entity, level, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ListTagsByEntityByLevelCsvWithHttpInfo = function(currency, entity, level, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`currency`)) {
        stop("Missing required parameter `currency`.")
      }

      if (missing(`entity`)) {
        stop("Missing required parameter `entity`.")
      }

      if (missing(`level`)) {
        stop("Missing required parameter `level`.")
      }

      queryParams['level'] <- level

      body <- NULL
      urlPath <- "/{currency}/entities/{entity}/tags.csv"
      if (!missing(`currency`)) {
        urlPath <- gsub(paste0("\\{", "currency", "\\}"), URLencode(as.character(`currency`), reserved = TRUE), urlPath)
      }

      if (!missing(`entity`)) {
        urlPath <- gsub(paste0("\\{", "entity", "\\}"), URLencode(as.character(`entity`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "character", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    SearchEntityNeighbors = function(currency, entity, direction, key, value, depth, breadth=16, skip.num.addresses=NULL, ...){
      apiResponse <- self$SearchEntityNeighborsWithHttpInfo(currency, entity, direction, key, value, depth, breadth, skip.num.addresses, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    SearchEntityNeighborsWithHttpInfo = function(currency, entity, direction, key, value, depth, breadth=16, skip.num.addresses=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`currency`)) {
        stop("Missing required parameter `currency`.")
      }

      if (missing(`entity`)) {
        stop("Missing required parameter `entity`.")
      }

      if (missing(`direction`)) {
        stop("Missing required parameter `direction`.")
      }

      if (missing(`key`)) {
        stop("Missing required parameter `key`.")
      }

      if (missing(`value`)) {
        stop("Missing required parameter `value`.")
      }

      if (missing(`depth`)) {
        stop("Missing required parameter `depth`.")
      }

      queryParams['direction'] <- direction

      queryParams['key'] <- key

      queryParams['value'] <- value

      queryParams['depth'] <- depth

      queryParams['breadth'] <- breadth

      queryParams['skip_num_addresses'] <- skip.num.addresses

      body <- NULL
      urlPath <- "/{currency}/entities/{entity}/search"
      if (!missing(`currency`)) {
        urlPath <- gsub(paste0("\\{", "currency", "\\}"), URLencode(as.character(`currency`), reserved = TRUE), urlPath)
      }

      if (!missing(`entity`)) {
        urlPath <- gsub(paste0("\\{", "entity", "\\}"), URLencode(as.character(`entity`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "array[SearchResultLevel1]", loadNamespace("openapi")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    }
  )
)
