# GraphSense API
#
# GraphSense API
#
# The version of the OpenAPI document: 0.5
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title GetTxIo
#'
#' @description GetTxIo Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field api  character 
#'
#' @field operation  character 
#'
#' @field parameters  list( \link{GetTxIoParameters} ) 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
GetTxIo <- R6::R6Class(
  'GetTxIo',
  public = list(
    `api` = NULL,
    `operation` = NULL,
    `parameters` = NULL,
    initialize = function(
        `api`, `operation`, `parameters`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`api`)) {
        stopifnot(is.character(`api`), length(`api`) == 1)
        self$`api` <- `api`
      }
      if (!missing(`operation`)) {
        stopifnot(is.character(`operation`), length(`operation`) == 1)
        self$`operation` <- `operation`
      }
      if (!missing(`parameters`)) {
        stopifnot(is.vector(`parameters`), length(`parameters`) != 0)
        sapply(`parameters`, function(x) stopifnot(R6::is.R6(x)))
        self$`parameters` <- `parameters`
      }
    },
    toJSON = function() {
      GetTxIoObject <- list()
      if (!is.null(self$`api`)) {
        GetTxIoObject[['api']] <-
          self$`api`
      }
      if (!is.null(self$`operation`)) {
        GetTxIoObject[['operation']] <-
          self$`operation`
      }
      if (!is.null(self$`parameters`)) {
        GetTxIoObject[['parameters']] <-
          lapply(self$`parameters`, function(x) x$toJSON())
      }

      GetTxIoObject
    },
    fromJSON = function(GetTxIoJson) {
      GetTxIoObject <- jsonlite::fromJSON(GetTxIoJson)
      if (!is.null(GetTxIoObject$`api`)) {
        self$`api` <- GetTxIoObject$`api`
      }
      if (!is.null(GetTxIoObject$`operation`)) {
        self$`operation` <- GetTxIoObject$`operation`
      }
      if (!is.null(GetTxIoObject$`parameters`)) {
        self$`parameters` <- ApiClient$new()$deserializeObj(GetTxIoObject$`parameters`, "array[GetTxIoParameters]", loadNamespace("openapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`api`)) {
        sprintf(
        '"api":
          "%s"
                ',
        self$`api`
        )},
        if (!is.null(self$`operation`)) {
        sprintf(
        '"operation":
          "%s"
                ',
        self$`operation`
        )},
        if (!is.null(self$`parameters`)) {
        sprintf(
        '"parameters":
        [%s]
',
        paste(sapply(self$`parameters`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(GetTxIoJson) {
      GetTxIoObject <- jsonlite::fromJSON(GetTxIoJson)
      self$`api` <- GetTxIoObject$`api`
      self$`operation` <- GetTxIoObject$`operation`
      self$`parameters` <- ApiClient$new()$deserializeObj(GetTxIoObject$`parameters`, "array[GetTxIoParameters]", loadNamespace("openapi"))
      self
    }
  )
)

