# GraphSense API
#
# GraphSense API
#
# The version of the OpenAPI document: 0.5
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Io
#'
#' @description Io Class
#'
#' @format An \code{R6Class} generator object
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Io <- R6::R6Class(
    "Io",
    public = list(
        initialize = function(...) {
            local.optional.var <- list(...)
            val <- unlist(local.optional.var)
            enumvec <- .parse_io()

            stopifnot(length(val) == 1L)

            if (!val %in% enumvec)
                stop("Use one of the valid values: ",
                    paste0(enumvec, collapse = ", "))
            private$value <- val
        },
        toJSON = function() {
            jsonlite::toJSON(private$value, auto_unbox = TRUE)
        },
        fromJSON = function(IoJson) {
            private$value <- jsonlite::fromJSON(IoJson,
                simplifyVector = FALSE)
            self
        },
        toJSONString = function() {
            as.character(jsonlite::toJSON(private$value,
                auto_unbox = TRUE))
        },
        fromJSONString = function(IoJson) {
            private$value <- jsonlite::fromJSON(IoJson,
                simplifyVector = FALSE)
            self
        }
    ),
    private = list(
        value = NULL
    )
)

# add to utils.R
.parse_io <- function(vals) {
    res <- gsub("^\\[|\\]$", "",
        "[inputs, outputs]"
    )
    unlist(strsplit(res, ", "))
}


