# GraphSense API
#
# GraphSense API
#
# The version of the OpenAPI document: 0.5.1-dev
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Link
#'
#' @description Link Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field height  integer 
#'
#' @field input_value  \link{Values} 
#'
#' @field output_value  \link{Values} 
#'
#' @field timestamp  integer 
#'
#' @field tx_hash  character 
#'
#' @field tx_type  character 
#'
#' @field from_address  character 
#'
#' @field to_address  character 
#'
#' @field value  \link{Values} 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Link <- R6::R6Class(
  'Link',
  public = list(
    `height` = NULL,
    `input_value` = NULL,
    `output_value` = NULL,
    `timestamp` = NULL,
    `tx_hash` = NULL,
    `tx_type` = NULL,
    `from_address` = NULL,
    `to_address` = NULL,
    `value` = NULL,
    initialize = function(
        `height`, `input_value`, `output_value`, `timestamp`, `tx_hash`, `tx_type`, `from_address`, `to_address`, `value`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`height`)) {
        stopifnot(is.numeric(`height`), length(`height`) == 1)
        self$`height` <- `height`
      }
      if (!missing(`input_value`)) {
        stopifnot(R6::is.R6(`input_value`))
        self$`input_value` <- `input_value`
      }
      if (!missing(`output_value`)) {
        stopifnot(R6::is.R6(`output_value`))
        self$`output_value` <- `output_value`
      }
      if (!missing(`timestamp`)) {
        stopifnot(is.numeric(`timestamp`), length(`timestamp`) == 1)
        self$`timestamp` <- `timestamp`
      }
      if (!missing(`tx_hash`)) {
        stopifnot(is.character(`tx_hash`), length(`tx_hash`) == 1)
        self$`tx_hash` <- `tx_hash`
      }
      if (!missing(`tx_type`)) {
        stopifnot(is.character(`tx_type`), length(`tx_type`) == 1)
        self$`tx_type` <- `tx_type`
      }
      if (!missing(`from_address`)) {
        stopifnot(is.character(`from_address`), length(`from_address`) == 1)
        self$`from_address` <- `from_address`
      }
      if (!missing(`to_address`)) {
        stopifnot(is.character(`to_address`), length(`to_address`) == 1)
        self$`to_address` <- `to_address`
      }
      if (!missing(`value`)) {
        stopifnot(R6::is.R6(`value`))
        self$`value` <- `value`
      }
    },
    toJSON = function() {
      LinkObject <- list()
      if (!is.null(self$`height`)) {
        LinkObject[['height']] <-
          self$`height`
      }
      if (!is.null(self$`input_value`)) {
        LinkObject[['input_value']] <-
          self$`input_value`$toJSON()
      }
      if (!is.null(self$`output_value`)) {
        LinkObject[['output_value']] <-
          self$`output_value`$toJSON()
      }
      if (!is.null(self$`timestamp`)) {
        LinkObject[['timestamp']] <-
          self$`timestamp`
      }
      if (!is.null(self$`tx_hash`)) {
        LinkObject[['tx_hash']] <-
          self$`tx_hash`
      }
      if (!is.null(self$`tx_type`)) {
        LinkObject[['tx_type']] <-
          self$`tx_type`
      }
      if (!is.null(self$`from_address`)) {
        LinkObject[['from_address']] <-
          self$`from_address`
      }
      if (!is.null(self$`to_address`)) {
        LinkObject[['to_address']] <-
          self$`to_address`
      }
      if (!is.null(self$`value`)) {
        LinkObject[['value']] <-
          self$`value`$toJSON()
      }

      LinkObject
    },
    fromJSON = function(LinkJson) {
      LinkObject <- jsonlite::fromJSON(LinkJson)
      if (!is.null(LinkObject$`height`)) {
        self$`height` <- LinkObject$`height`
      }
      if (!is.null(LinkObject$`input_value`)) {
        input_valueObject <- Values$new()
        input_valueObject$fromJSON(jsonlite::toJSON(LinkObject$input_value, auto_unbox = TRUE, digits = NA))
        self$`input_value` <- input_valueObject
      }
      if (!is.null(LinkObject$`output_value`)) {
        output_valueObject <- Values$new()
        output_valueObject$fromJSON(jsonlite::toJSON(LinkObject$output_value, auto_unbox = TRUE, digits = NA))
        self$`output_value` <- output_valueObject
      }
      if (!is.null(LinkObject$`timestamp`)) {
        self$`timestamp` <- LinkObject$`timestamp`
      }
      if (!is.null(LinkObject$`tx_hash`)) {
        self$`tx_hash` <- LinkObject$`tx_hash`
      }
      if (!is.null(LinkObject$`tx_type`)) {
        self$`tx_type` <- LinkObject$`tx_type`
      }
      if (!is.null(LinkObject$`from_address`)) {
        self$`from_address` <- LinkObject$`from_address`
      }
      if (!is.null(LinkObject$`to_address`)) {
        self$`to_address` <- LinkObject$`to_address`
      }
      if (!is.null(LinkObject$`value`)) {
        valueObject <- Values$new()
        valueObject$fromJSON(jsonlite::toJSON(LinkObject$value, auto_unbox = TRUE, digits = NA))
        self$`value` <- valueObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`height`)) {
        sprintf(
        '"height":
          %d
                ',
        self$`height`
        )},
        if (!is.null(self$`input_value`)) {
        sprintf(
        '"input_value":
        %s
        ',
        jsonlite::toJSON(self$`input_value`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`output_value`)) {
        sprintf(
        '"output_value":
        %s
        ',
        jsonlite::toJSON(self$`output_value`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`timestamp`)) {
        sprintf(
        '"timestamp":
          %d
                ',
        self$`timestamp`
        )},
        if (!is.null(self$`tx_hash`)) {
        sprintf(
        '"tx_hash":
          "%s"
                ',
        self$`tx_hash`
        )},
        if (!is.null(self$`tx_type`)) {
        sprintf(
        '"tx_type":
          "%s"
                ',
        self$`tx_type`
        )},
        if (!is.null(self$`from_address`)) {
        sprintf(
        '"from_address":
          "%s"
                ',
        self$`from_address`
        )},
        if (!is.null(self$`to_address`)) {
        sprintf(
        '"to_address":
          "%s"
                ',
        self$`to_address`
        )},
        if (!is.null(self$`value`)) {
        sprintf(
        '"value":
        %s
        ',
        jsonlite::toJSON(self$`value`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(LinkJson) {
      LinkObject <- jsonlite::fromJSON(LinkJson)
      self$`height` <- LinkObject$`height`
      self$`input_value` <- Values$new()$fromJSON(jsonlite::toJSON(LinkObject$input_value, auto_unbox = TRUE, digits = NA))
      self$`output_value` <- Values$new()$fromJSON(jsonlite::toJSON(LinkObject$output_value, auto_unbox = TRUE, digits = NA))
      self$`timestamp` <- LinkObject$`timestamp`
      self$`tx_hash` <- LinkObject$`tx_hash`
      self$`tx_type` <- LinkObject$`tx_type`
      self$`from_address` <- LinkObject$`from_address`
      self$`to_address` <- LinkObject$`to_address`
      self$`value` <- Values$new()$fromJSON(jsonlite::toJSON(LinkObject$value, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)

