# GraphSense API
#
# GraphSense API
#
# The version of the OpenAPI document: 0.5
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Link
#'
#' @description Link Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field currency_type  character 
#'
#' @field height  integer 
#'
#' @field input_value  \link{Values} 
#'
#' @field output_value  \link{Values} 
#'
#' @field timestamp  integer 
#'
#' @field tx_hash  character 
#'
#' @field values  \link{Values} 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Link <- R6::R6Class(
  'Link',
  public = list(
    `currency_type` = NULL,
    `height` = NULL,
    `input_value` = NULL,
    `output_value` = NULL,
    `timestamp` = NULL,
    `tx_hash` = NULL,
    `values` = NULL,
    initialize = function(
        `currency_type`, `height`, `input_value`, `output_value`, `timestamp`, `tx_hash`, `values`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`currency_type`)) {
        stopifnot(is.character(`currency_type`), length(`currency_type`) == 1)
        self$`currency_type` <- `currency_type`
      }
      if (!missing(`height`)) {
        stopifnot(is.numeric(`height`), length(`height`) == 1)
        self$`height` <- `height`
      }
      if (!missing(`input_value`)) {
        stopifnot(R6::is.R6(`input_value`))
        self$`input_value` <- `input_value`
      }
      if (!missing(`output_value`)) {
        stopifnot(R6::is.R6(`output_value`))
        self$`output_value` <- `output_value`
      }
      if (!missing(`timestamp`)) {
        stopifnot(is.numeric(`timestamp`), length(`timestamp`) == 1)
        self$`timestamp` <- `timestamp`
      }
      if (!missing(`tx_hash`)) {
        stopifnot(is.character(`tx_hash`), length(`tx_hash`) == 1)
        self$`tx_hash` <- `tx_hash`
      }
      if (!missing(`values`)) {
        stopifnot(R6::is.R6(`values`))
        self$`values` <- `values`
      }
    },
    toJSON = function() {
      LinkObject <- list()
      if (!is.null(self$`currency_type`)) {
        LinkObject[['currency_type']] <-
          self$`currency_type`
      }
      if (!is.null(self$`height`)) {
        LinkObject[['height']] <-
          self$`height`
      }
      if (!is.null(self$`input_value`)) {
        LinkObject[['input_value']] <-
          self$`input_value`$toJSON()
      }
      if (!is.null(self$`output_value`)) {
        LinkObject[['output_value']] <-
          self$`output_value`$toJSON()
      }
      if (!is.null(self$`timestamp`)) {
        LinkObject[['timestamp']] <-
          self$`timestamp`
      }
      if (!is.null(self$`tx_hash`)) {
        LinkObject[['tx_hash']] <-
          self$`tx_hash`
      }
      if (!is.null(self$`values`)) {
        LinkObject[['values']] <-
          self$`values`$toJSON()
      }

      LinkObject
    },
    fromJSON = function(LinkJson) {
      LinkObject <- jsonlite::fromJSON(LinkJson)
      if (!is.null(LinkObject$`currency_type`)) {
        self$`currency_type` <- LinkObject$`currency_type`
      }
      if (!is.null(LinkObject$`height`)) {
        self$`height` <- LinkObject$`height`
      }
      if (!is.null(LinkObject$`input_value`)) {
        input_valueObject <- Values$new()
        input_valueObject$fromJSON(jsonlite::toJSON(LinkObject$input_value, auto_unbox = TRUE, digits = NA))
        self$`input_value` <- input_valueObject
      }
      if (!is.null(LinkObject$`output_value`)) {
        output_valueObject <- Values$new()
        output_valueObject$fromJSON(jsonlite::toJSON(LinkObject$output_value, auto_unbox = TRUE, digits = NA))
        self$`output_value` <- output_valueObject
      }
      if (!is.null(LinkObject$`timestamp`)) {
        self$`timestamp` <- LinkObject$`timestamp`
      }
      if (!is.null(LinkObject$`tx_hash`)) {
        self$`tx_hash` <- LinkObject$`tx_hash`
      }
      if (!is.null(LinkObject$`values`)) {
        valuesObject <- Values$new()
        valuesObject$fromJSON(jsonlite::toJSON(LinkObject$values, auto_unbox = TRUE, digits = NA))
        self$`values` <- valuesObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`currency_type`)) {
        sprintf(
        '"currency_type":
          "%s"
                ',
        self$`currency_type`
        )},
        if (!is.null(self$`height`)) {
        sprintf(
        '"height":
          %d
                ',
        self$`height`
        )},
        if (!is.null(self$`input_value`)) {
        sprintf(
        '"input_value":
        %s
        ',
        jsonlite::toJSON(self$`input_value`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`output_value`)) {
        sprintf(
        '"output_value":
        %s
        ',
        jsonlite::toJSON(self$`output_value`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`timestamp`)) {
        sprintf(
        '"timestamp":
          %d
                ',
        self$`timestamp`
        )},
        if (!is.null(self$`tx_hash`)) {
        sprintf(
        '"tx_hash":
          "%s"
                ',
        self$`tx_hash`
        )},
        if (!is.null(self$`values`)) {
        sprintf(
        '"values":
        %s
        ',
        jsonlite::toJSON(self$`values`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(LinkJson) {
      LinkObject <- jsonlite::fromJSON(LinkJson)
      self$`currency_type` <- LinkObject$`currency_type`
      self$`height` <- LinkObject$`height`
      self$`input_value` <- Values$new()$fromJSON(jsonlite::toJSON(LinkObject$input_value, auto_unbox = TRUE, digits = NA))
      self$`output_value` <- Values$new()$fromJSON(jsonlite::toJSON(LinkObject$output_value, auto_unbox = TRUE, digits = NA))
      self$`timestamp` <- LinkObject$`timestamp`
      self$`tx_hash` <- LinkObject$`tx_hash`
      self$`values` <- Values$new()$fromJSON(jsonlite::toJSON(LinkObject$values, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)

