# GraphSense API
#
# GraphSense API
#
# The version of the OpenAPI document: 0.5
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title LinkUtxo
#'
#' @description LinkUtxo Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field currency_type  character 
#'
#' @field tx_hash  character 
#'
#' @field height  integer 
#'
#' @field timestamp  integer 
#'
#' @field input_value  \link{Values} 
#'
#' @field output_value  \link{Values} 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
LinkUtxo <- R6::R6Class(
  'LinkUtxo',
  public = list(
    `currency_type` = NULL,
    `tx_hash` = NULL,
    `height` = NULL,
    `timestamp` = NULL,
    `input_value` = NULL,
    `output_value` = NULL,
    initialize = function(
        `currency_type`, `tx_hash`, `height`, `timestamp`, `input_value`, `output_value`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`currency_type`)) {
        stopifnot(is.character(`currency_type`), length(`currency_type`) == 1)
        self$`currency_type` <- `currency_type`
      }
      if (!missing(`tx_hash`)) {
        stopifnot(is.character(`tx_hash`), length(`tx_hash`) == 1)
        self$`tx_hash` <- `tx_hash`
      }
      if (!missing(`height`)) {
        stopifnot(is.numeric(`height`), length(`height`) == 1)
        self$`height` <- `height`
      }
      if (!missing(`timestamp`)) {
        stopifnot(is.numeric(`timestamp`), length(`timestamp`) == 1)
        self$`timestamp` <- `timestamp`
      }
      if (!missing(`input_value`)) {
        stopifnot(R6::is.R6(`input_value`))
        self$`input_value` <- `input_value`
      }
      if (!missing(`output_value`)) {
        stopifnot(R6::is.R6(`output_value`))
        self$`output_value` <- `output_value`
      }
    },
    toJSON = function() {
      LinkUtxoObject <- list()
      if (!is.null(self$`currency_type`)) {
        LinkUtxoObject[['currency_type']] <-
          self$`currency_type`
      }
      if (!is.null(self$`tx_hash`)) {
        LinkUtxoObject[['tx_hash']] <-
          self$`tx_hash`
      }
      if (!is.null(self$`height`)) {
        LinkUtxoObject[['height']] <-
          self$`height`
      }
      if (!is.null(self$`timestamp`)) {
        LinkUtxoObject[['timestamp']] <-
          self$`timestamp`
      }
      if (!is.null(self$`input_value`)) {
        LinkUtxoObject[['input_value']] <-
          self$`input_value`$toJSON()
      }
      if (!is.null(self$`output_value`)) {
        LinkUtxoObject[['output_value']] <-
          self$`output_value`$toJSON()
      }

      LinkUtxoObject
    },
    fromJSON = function(LinkUtxoJson) {
      LinkUtxoObject <- jsonlite::fromJSON(LinkUtxoJson)
      if (!is.null(LinkUtxoObject$`currency_type`)) {
        self$`currency_type` <- LinkUtxoObject$`currency_type`
      }
      if (!is.null(LinkUtxoObject$`tx_hash`)) {
        self$`tx_hash` <- LinkUtxoObject$`tx_hash`
      }
      if (!is.null(LinkUtxoObject$`height`)) {
        self$`height` <- LinkUtxoObject$`height`
      }
      if (!is.null(LinkUtxoObject$`timestamp`)) {
        self$`timestamp` <- LinkUtxoObject$`timestamp`
      }
      if (!is.null(LinkUtxoObject$`input_value`)) {
        input_valueObject <- Values$new()
        input_valueObject$fromJSON(jsonlite::toJSON(LinkUtxoObject$input_value, auto_unbox = TRUE, digits = NA))
        self$`input_value` <- input_valueObject
      }
      if (!is.null(LinkUtxoObject$`output_value`)) {
        output_valueObject <- Values$new()
        output_valueObject$fromJSON(jsonlite::toJSON(LinkUtxoObject$output_value, auto_unbox = TRUE, digits = NA))
        self$`output_value` <- output_valueObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`currency_type`)) {
        sprintf(
        '"currency_type":
          "%s"
                ',
        self$`currency_type`
        )},
        if (!is.null(self$`tx_hash`)) {
        sprintf(
        '"tx_hash":
          "%s"
                ',
        self$`tx_hash`
        )},
        if (!is.null(self$`height`)) {
        sprintf(
        '"height":
          %d
                ',
        self$`height`
        )},
        if (!is.null(self$`timestamp`)) {
        sprintf(
        '"timestamp":
          %d
                ',
        self$`timestamp`
        )},
        if (!is.null(self$`input_value`)) {
        sprintf(
        '"input_value":
        %s
        ',
        jsonlite::toJSON(self$`input_value`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`output_value`)) {
        sprintf(
        '"output_value":
        %s
        ',
        jsonlite::toJSON(self$`output_value`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(LinkUtxoJson) {
      LinkUtxoObject <- jsonlite::fromJSON(LinkUtxoJson)
      self$`currency_type` <- LinkUtxoObject$`currency_type`
      self$`tx_hash` <- LinkUtxoObject$`tx_hash`
      self$`height` <- LinkUtxoObject$`height`
      self$`timestamp` <- LinkUtxoObject$`timestamp`
      self$`input_value` <- Values$new()$fromJSON(jsonlite::toJSON(LinkUtxoObject$input_value, auto_unbox = TRUE, digits = NA))
      self$`output_value` <- Values$new()$fromJSON(jsonlite::toJSON(LinkUtxoObject$output_value, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)

