# GraphSense API
#
# GraphSense API
#
# The version of the OpenAPI document: 0.5
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Rates
#'
#' @description Rates Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field height  integer [optional]
#'
#' @field rates  \link{RatesRates} [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Rates <- R6::R6Class(
  'Rates',
  public = list(
    `height` = NULL,
    `rates` = NULL,
    initialize = function(
        `height`=NULL, `rates`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`height`)) {
        stopifnot(is.numeric(`height`), length(`height`) == 1)
        self$`height` <- `height`
      }
      if (!is.null(`rates`)) {
        stopifnot(R6::is.R6(`rates`))
        self$`rates` <- `rates`
      }
    },
    toJSON = function() {
      RatesObject <- list()
      if (!is.null(self$`height`)) {
        RatesObject[['height']] <-
          self$`height`
      }
      if (!is.null(self$`rates`)) {
        RatesObject[['rates']] <-
          self$`rates`$toJSON()
      }

      RatesObject
    },
    fromJSON = function(RatesJson) {
      RatesObject <- jsonlite::fromJSON(RatesJson)
      if (!is.null(RatesObject$`height`)) {
        self$`height` <- RatesObject$`height`
      }
      if (!is.null(RatesObject$`rates`)) {
        ratesObject <- RatesRates$new()
        ratesObject$fromJSON(jsonlite::toJSON(RatesObject$rates, auto_unbox = TRUE, digits = NA))
        self$`rates` <- ratesObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`height`)) {
        sprintf(
        '"height":
          %d
                ',
        self$`height`
        )},
        if (!is.null(self$`rates`)) {
        sprintf(
        '"rates":
        %s
        ',
        jsonlite::toJSON(self$`rates`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(RatesJson) {
      RatesObject <- jsonlite::fromJSON(RatesJson)
      self$`height` <- RatesObject$`height`
      self$`rates` <- RatesRates$new()$fromJSON(jsonlite::toJSON(RatesObject$rates, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)

