# GraphSense API
#
# GraphSense API
#
# The version of the OpenAPI document: 0.5.1-dev
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title StatsLedger
#'
#' @description StatsLedger Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field id  character [optional]
#'
#' @field report_uuid  character [optional]
#'
#' @field version  \link{StatsLedgerVersion} [optional]
#'
#' @field visible_name  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
StatsLedger <- R6::R6Class(
  'StatsLedger',
  public = list(
    `id` = NULL,
    `report_uuid` = NULL,
    `version` = NULL,
    `visible_name` = NULL,
    initialize = function(
        `id`=NULL, `report_uuid`=NULL, `version`=NULL, `visible_name`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`report_uuid`)) {
        stopifnot(is.character(`report_uuid`), length(`report_uuid`) == 1)
        self$`report_uuid` <- `report_uuid`
      }
      if (!is.null(`version`)) {
        stopifnot(R6::is.R6(`version`))
        self$`version` <- `version`
      }
      if (!is.null(`visible_name`)) {
        stopifnot(is.character(`visible_name`), length(`visible_name`) == 1)
        self$`visible_name` <- `visible_name`
      }
    },
    toJSON = function() {
      StatsLedgerObject <- list()
      if (!is.null(self$`id`)) {
        StatsLedgerObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`report_uuid`)) {
        StatsLedgerObject[['report_uuid']] <-
          self$`report_uuid`
      }
      if (!is.null(self$`version`)) {
        StatsLedgerObject[['version']] <-
          self$`version`$toJSON()
      }
      if (!is.null(self$`visible_name`)) {
        StatsLedgerObject[['visible_name']] <-
          self$`visible_name`
      }

      StatsLedgerObject
    },
    fromJSON = function(StatsLedgerJson) {
      StatsLedgerObject <- jsonlite::fromJSON(StatsLedgerJson)
      if (!is.null(StatsLedgerObject$`id`)) {
        self$`id` <- StatsLedgerObject$`id`
      }
      if (!is.null(StatsLedgerObject$`report_uuid`)) {
        self$`report_uuid` <- StatsLedgerObject$`report_uuid`
      }
      if (!is.null(StatsLedgerObject$`version`)) {
        versionObject <- StatsLedgerVersion$new()
        versionObject$fromJSON(jsonlite::toJSON(StatsLedgerObject$version, auto_unbox = TRUE, digits = NA))
        self$`version` <- versionObject
      }
      if (!is.null(StatsLedgerObject$`visible_name`)) {
        self$`visible_name` <- StatsLedgerObject$`visible_name`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`report_uuid`)) {
        sprintf(
        '"report_uuid":
          "%s"
                ',
        self$`report_uuid`
        )},
        if (!is.null(self$`version`)) {
        sprintf(
        '"version":
        %s
        ',
        jsonlite::toJSON(self$`version`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`visible_name`)) {
        sprintf(
        '"visible_name":
          "%s"
                ',
        self$`visible_name`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(StatsLedgerJson) {
      StatsLedgerObject <- jsonlite::fromJSON(StatsLedgerJson)
      self$`id` <- StatsLedgerObject$`id`
      self$`report_uuid` <- StatsLedgerObject$`report_uuid`
      self$`version` <- StatsLedgerVersion$new()$fromJSON(jsonlite::toJSON(StatsLedgerObject$version, auto_unbox = TRUE, digits = NA))
      self$`visible_name` <- StatsLedgerObject$`visible_name`
      self
    }
  )
)

