# GraphSense API
#
# GraphSense API
#
# The version of the OpenAPI document: 0.5.1-dev
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title StatsNote
#'
#' @description StatsNote Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field note  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
StatsNote <- R6::R6Class(
  'StatsNote',
  public = list(
    `note` = NULL,
    initialize = function(
        `note`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`note`)) {
        stopifnot(is.character(`note`), length(`note`) == 1)
        self$`note` <- `note`
      }
    },
    toJSON = function() {
      StatsNoteObject <- list()
      if (!is.null(self$`note`)) {
        StatsNoteObject[['note']] <-
          self$`note`
      }

      StatsNoteObject
    },
    fromJSON = function(StatsNoteJson) {
      StatsNoteObject <- jsonlite::fromJSON(StatsNoteJson)
      if (!is.null(StatsNoteObject$`note`)) {
        self$`note` <- StatsNoteObject$`note`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`note`)) {
        sprintf(
        '"note":
          "%s"
                ',
        self$`note`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(StatsNoteJson) {
      StatsNoteObject <- jsonlite::fromJSON(StatsNoteJson)
      self$`note` <- StatsNoteObject$`note`
      self
    }
  )
)

