# GraphSense API
#
# GraphSense API
#
# The version of the OpenAPI document: 0.5
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Tag
#'
#' @description Tag Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field label  character 
#'
#' @field category  character [optional]
#'
#' @field abuse  character [optional]
#'
#' @field tagpack_uri  character [optional]
#'
#' @field source  character [optional]
#'
#' @field lastmod  integer [optional]
#'
#' @field active  character 
#'
#' @field currency  character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Tag <- R6::R6Class(
  'Tag',
  public = list(
    `label` = NULL,
    `category` = NULL,
    `abuse` = NULL,
    `tagpack_uri` = NULL,
    `source` = NULL,
    `lastmod` = NULL,
    `active` = NULL,
    `currency` = NULL,
    initialize = function(
        `label`, `active`, `currency`, `category`=NULL, `abuse`=NULL, `tagpack_uri`=NULL, `source`=NULL, `lastmod`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`label`)) {
        stopifnot(is.character(`label`), length(`label`) == 1)
        self$`label` <- `label`
      }
      if (!missing(`active`)) {
        self$`active` <- `active`
      }
      if (!missing(`currency`)) {
        stopifnot(is.character(`currency`), length(`currency`) == 1)
        self$`currency` <- `currency`
      }
      if (!is.null(`category`)) {
        stopifnot(is.character(`category`), length(`category`) == 1)
        self$`category` <- `category`
      }
      if (!is.null(`abuse`)) {
        stopifnot(is.character(`abuse`), length(`abuse`) == 1)
        self$`abuse` <- `abuse`
      }
      if (!is.null(`tagpack_uri`)) {
        stopifnot(is.character(`tagpack_uri`), length(`tagpack_uri`) == 1)
        self$`tagpack_uri` <- `tagpack_uri`
      }
      if (!is.null(`source`)) {
        stopifnot(is.character(`source`), length(`source`) == 1)
        self$`source` <- `source`
      }
      if (!is.null(`lastmod`)) {
        stopifnot(is.numeric(`lastmod`), length(`lastmod`) == 1)
        self$`lastmod` <- `lastmod`
      }
    },
    toJSON = function() {
      TagObject <- list()
      if (!is.null(self$`label`)) {
        TagObject[['label']] <-
          self$`label`
      }
      if (!is.null(self$`category`)) {
        TagObject[['category']] <-
          self$`category`
      }
      if (!is.null(self$`abuse`)) {
        TagObject[['abuse']] <-
          self$`abuse`
      }
      if (!is.null(self$`tagpack_uri`)) {
        TagObject[['tagpack_uri']] <-
          self$`tagpack_uri`
      }
      if (!is.null(self$`source`)) {
        TagObject[['source']] <-
          self$`source`
      }
      if (!is.null(self$`lastmod`)) {
        TagObject[['lastmod']] <-
          self$`lastmod`
      }
      if (!is.null(self$`active`)) {
        TagObject[['active']] <-
          self$`active`
      }
      if (!is.null(self$`currency`)) {
        TagObject[['currency']] <-
          self$`currency`
      }

      TagObject
    },
    fromJSON = function(TagJson) {
      TagObject <- jsonlite::fromJSON(TagJson)
      if (!is.null(TagObject$`label`)) {
        self$`label` <- TagObject$`label`
      }
      if (!is.null(TagObject$`category`)) {
        self$`category` <- TagObject$`category`
      }
      if (!is.null(TagObject$`abuse`)) {
        self$`abuse` <- TagObject$`abuse`
      }
      if (!is.null(TagObject$`tagpack_uri`)) {
        self$`tagpack_uri` <- TagObject$`tagpack_uri`
      }
      if (!is.null(TagObject$`source`)) {
        self$`source` <- TagObject$`source`
      }
      if (!is.null(TagObject$`lastmod`)) {
        self$`lastmod` <- TagObject$`lastmod`
      }
      if (!is.null(TagObject$`active`)) {
        self$`active` <- TagObject$`active`
      }
      if (!is.null(TagObject$`currency`)) {
        self$`currency` <- TagObject$`currency`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`label`)) {
        sprintf(
        '"label":
          "%s"
                ',
        self$`label`
        )},
        if (!is.null(self$`category`)) {
        sprintf(
        '"category":
          "%s"
                ',
        self$`category`
        )},
        if (!is.null(self$`abuse`)) {
        sprintf(
        '"abuse":
          "%s"
                ',
        self$`abuse`
        )},
        if (!is.null(self$`tagpack_uri`)) {
        sprintf(
        '"tagpack_uri":
          "%s"
                ',
        self$`tagpack_uri`
        )},
        if (!is.null(self$`source`)) {
        sprintf(
        '"source":
          "%s"
                ',
        self$`source`
        )},
        if (!is.null(self$`lastmod`)) {
        sprintf(
        '"lastmod":
          %d
                ',
        self$`lastmod`
        )},
        if (!is.null(self$`active`)) {
        sprintf(
        '"active":
          "%s"
                ',
        self$`active`
        )},
        if (!is.null(self$`currency`)) {
        sprintf(
        '"currency":
          "%s"
                ',
        self$`currency`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(TagJson) {
      TagObject <- jsonlite::fromJSON(TagJson)
      self$`label` <- TagObject$`label`
      self$`category` <- TagObject$`category`
      self$`abuse` <- TagObject$`abuse`
      self$`tagpack_uri` <- TagObject$`tagpack_uri`
      self$`source` <- TagObject$`source`
      self$`lastmod` <- TagObject$`lastmod`
      self$`active` <- TagObject$`active`
      self$`currency` <- TagObject$`currency`
      self
    }
  )
)

