# GraphSense API
#
# GraphSense API
#
# The version of the OpenAPI document: 0.5
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Tx
#'
#' @description Tx Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field currency_type  character 
#'
#' @field tx_hash  character 
#'
#' @field coinbase  character 
#'
#' @field height  integer 
#'
#' @field inputs  list( \link{TxValue} ) 
#'
#' @field outputs  list( \link{TxValue} ) 
#'
#' @field timestamp  integer 
#'
#' @field total_input  \link{Values} 
#'
#' @field total_output  \link{Values} 
#'
#' @field values  \link{Values} 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Tx <- R6::R6Class(
  'Tx',
  public = list(
    `currency_type` = NULL,
    `tx_hash` = NULL,
    `coinbase` = NULL,
    `height` = NULL,
    `inputs` = NULL,
    `outputs` = NULL,
    `timestamp` = NULL,
    `total_input` = NULL,
    `total_output` = NULL,
    `values` = NULL,
    initialize = function(
        `currency_type`, `tx_hash`, `coinbase`, `height`, `inputs`, `outputs`, `timestamp`, `total_input`, `total_output`, `values`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`currency_type`)) {
        stopifnot(is.character(`currency_type`), length(`currency_type`) == 1)
        self$`currency_type` <- `currency_type`
      }
      if (!missing(`tx_hash`)) {
        stopifnot(is.character(`tx_hash`), length(`tx_hash`) == 1)
        self$`tx_hash` <- `tx_hash`
      }
      if (!missing(`coinbase`)) {
        self$`coinbase` <- `coinbase`
      }
      if (!missing(`height`)) {
        stopifnot(is.numeric(`height`), length(`height`) == 1)
        self$`height` <- `height`
      }
      if (!missing(`inputs`)) {
        stopifnot(is.vector(`inputs`), length(`inputs`) != 0)
        sapply(`inputs`, function(x) stopifnot(R6::is.R6(x)))
        self$`inputs` <- `inputs`
      }
      if (!missing(`outputs`)) {
        stopifnot(is.vector(`outputs`), length(`outputs`) != 0)
        sapply(`outputs`, function(x) stopifnot(R6::is.R6(x)))
        self$`outputs` <- `outputs`
      }
      if (!missing(`timestamp`)) {
        stopifnot(is.numeric(`timestamp`), length(`timestamp`) == 1)
        self$`timestamp` <- `timestamp`
      }
      if (!missing(`total_input`)) {
        stopifnot(R6::is.R6(`total_input`))
        self$`total_input` <- `total_input`
      }
      if (!missing(`total_output`)) {
        stopifnot(R6::is.R6(`total_output`))
        self$`total_output` <- `total_output`
      }
      if (!missing(`values`)) {
        stopifnot(R6::is.R6(`values`))
        self$`values` <- `values`
      }
    },
    toJSON = function() {
      TxObject <- list()
      if (!is.null(self$`currency_type`)) {
        TxObject[['currency_type']] <-
          self$`currency_type`
      }
      if (!is.null(self$`tx_hash`)) {
        TxObject[['tx_hash']] <-
          self$`tx_hash`
      }
      if (!is.null(self$`coinbase`)) {
        TxObject[['coinbase']] <-
          self$`coinbase`
      }
      if (!is.null(self$`height`)) {
        TxObject[['height']] <-
          self$`height`
      }
      if (!is.null(self$`inputs`)) {
        TxObject[['inputs']] <-
          lapply(self$`inputs`, function(x) x$toJSON())
      }
      if (!is.null(self$`outputs`)) {
        TxObject[['outputs']] <-
          lapply(self$`outputs`, function(x) x$toJSON())
      }
      if (!is.null(self$`timestamp`)) {
        TxObject[['timestamp']] <-
          self$`timestamp`
      }
      if (!is.null(self$`total_input`)) {
        TxObject[['total_input']] <-
          self$`total_input`$toJSON()
      }
      if (!is.null(self$`total_output`)) {
        TxObject[['total_output']] <-
          self$`total_output`$toJSON()
      }
      if (!is.null(self$`values`)) {
        TxObject[['values']] <-
          self$`values`$toJSON()
      }

      TxObject
    },
    fromJSON = function(TxJson) {
      TxObject <- jsonlite::fromJSON(TxJson)
      if (!is.null(TxObject$`currency_type`)) {
        self$`currency_type` <- TxObject$`currency_type`
      }
      if (!is.null(TxObject$`tx_hash`)) {
        self$`tx_hash` <- TxObject$`tx_hash`
      }
      if (!is.null(TxObject$`coinbase`)) {
        self$`coinbase` <- TxObject$`coinbase`
      }
      if (!is.null(TxObject$`height`)) {
        self$`height` <- TxObject$`height`
      }
      if (!is.null(TxObject$`inputs`)) {
        self$`inputs` <- ApiClient$new()$deserializeObj(TxObject$`inputs`, "array[TxValue]", loadNamespace("openapi"))
      }
      if (!is.null(TxObject$`outputs`)) {
        self$`outputs` <- ApiClient$new()$deserializeObj(TxObject$`outputs`, "array[TxValue]", loadNamespace("openapi"))
      }
      if (!is.null(TxObject$`timestamp`)) {
        self$`timestamp` <- TxObject$`timestamp`
      }
      if (!is.null(TxObject$`total_input`)) {
        total_inputObject <- Values$new()
        total_inputObject$fromJSON(jsonlite::toJSON(TxObject$total_input, auto_unbox = TRUE, digits = NA))
        self$`total_input` <- total_inputObject
      }
      if (!is.null(TxObject$`total_output`)) {
        total_outputObject <- Values$new()
        total_outputObject$fromJSON(jsonlite::toJSON(TxObject$total_output, auto_unbox = TRUE, digits = NA))
        self$`total_output` <- total_outputObject
      }
      if (!is.null(TxObject$`values`)) {
        valuesObject <- Values$new()
        valuesObject$fromJSON(jsonlite::toJSON(TxObject$values, auto_unbox = TRUE, digits = NA))
        self$`values` <- valuesObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`currency_type`)) {
        sprintf(
        '"currency_type":
          "%s"
                ',
        self$`currency_type`
        )},
        if (!is.null(self$`tx_hash`)) {
        sprintf(
        '"tx_hash":
          "%s"
                ',
        self$`tx_hash`
        )},
        if (!is.null(self$`coinbase`)) {
        sprintf(
        '"coinbase":
          "%s"
                ',
        self$`coinbase`
        )},
        if (!is.null(self$`height`)) {
        sprintf(
        '"height":
          %d
                ',
        self$`height`
        )},
        if (!is.null(self$`inputs`)) {
        sprintf(
        '"inputs":
        [%s]
',
        paste(sapply(self$`inputs`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`outputs`)) {
        sprintf(
        '"outputs":
        [%s]
',
        paste(sapply(self$`outputs`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`timestamp`)) {
        sprintf(
        '"timestamp":
          %d
                ',
        self$`timestamp`
        )},
        if (!is.null(self$`total_input`)) {
        sprintf(
        '"total_input":
        %s
        ',
        jsonlite::toJSON(self$`total_input`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`total_output`)) {
        sprintf(
        '"total_output":
        %s
        ',
        jsonlite::toJSON(self$`total_output`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`values`)) {
        sprintf(
        '"values":
        %s
        ',
        jsonlite::toJSON(self$`values`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(TxJson) {
      TxObject <- jsonlite::fromJSON(TxJson)
      self$`currency_type` <- TxObject$`currency_type`
      self$`tx_hash` <- TxObject$`tx_hash`
      self$`coinbase` <- TxObject$`coinbase`
      self$`height` <- TxObject$`height`
      self$`inputs` <- ApiClient$new()$deserializeObj(TxObject$`inputs`, "array[TxValue]", loadNamespace("openapi"))
      self$`outputs` <- ApiClient$new()$deserializeObj(TxObject$`outputs`, "array[TxValue]", loadNamespace("openapi"))
      self$`timestamp` <- TxObject$`timestamp`
      self$`total_input` <- Values$new()$fromJSON(jsonlite::toJSON(TxObject$total_input, auto_unbox = TRUE, digits = NA))
      self$`total_output` <- Values$new()$fromJSON(jsonlite::toJSON(TxObject$total_output, auto_unbox = TRUE, digits = NA))
      self$`values` <- Values$new()$fromJSON(jsonlite::toJSON(TxObject$values, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)

