# GraphSense API
#
# GraphSense API
#
# The version of the OpenAPI document: 0.5
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title TxAccount
#'
#' @description TxAccount Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field currency_type  character 
#'
#' @field tx_hash  character 
#'
#' @field height  integer 
#'
#' @field timestamp  integer 
#'
#' @field values  \link{Values} 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
TxAccount <- R6::R6Class(
  'TxAccount',
  public = list(
    `currency_type` = NULL,
    `tx_hash` = NULL,
    `height` = NULL,
    `timestamp` = NULL,
    `values` = NULL,
    initialize = function(
        `currency_type`, `tx_hash`, `height`, `timestamp`, `values`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`currency_type`)) {
        stopifnot(is.character(`currency_type`), length(`currency_type`) == 1)
        self$`currency_type` <- `currency_type`
      }
      if (!missing(`tx_hash`)) {
        stopifnot(is.character(`tx_hash`), length(`tx_hash`) == 1)
        self$`tx_hash` <- `tx_hash`
      }
      if (!missing(`height`)) {
        stopifnot(is.numeric(`height`), length(`height`) == 1)
        self$`height` <- `height`
      }
      if (!missing(`timestamp`)) {
        stopifnot(is.numeric(`timestamp`), length(`timestamp`) == 1)
        self$`timestamp` <- `timestamp`
      }
      if (!missing(`values`)) {
        stopifnot(R6::is.R6(`values`))
        self$`values` <- `values`
      }
    },
    toJSON = function() {
      TxAccountObject <- list()
      if (!is.null(self$`currency_type`)) {
        TxAccountObject[['currency_type']] <-
          self$`currency_type`
      }
      if (!is.null(self$`tx_hash`)) {
        TxAccountObject[['tx_hash']] <-
          self$`tx_hash`
      }
      if (!is.null(self$`height`)) {
        TxAccountObject[['height']] <-
          self$`height`
      }
      if (!is.null(self$`timestamp`)) {
        TxAccountObject[['timestamp']] <-
          self$`timestamp`
      }
      if (!is.null(self$`values`)) {
        TxAccountObject[['values']] <-
          self$`values`$toJSON()
      }

      TxAccountObject
    },
    fromJSON = function(TxAccountJson) {
      TxAccountObject <- jsonlite::fromJSON(TxAccountJson)
      if (!is.null(TxAccountObject$`currency_type`)) {
        self$`currency_type` <- TxAccountObject$`currency_type`
      }
      if (!is.null(TxAccountObject$`tx_hash`)) {
        self$`tx_hash` <- TxAccountObject$`tx_hash`
      }
      if (!is.null(TxAccountObject$`height`)) {
        self$`height` <- TxAccountObject$`height`
      }
      if (!is.null(TxAccountObject$`timestamp`)) {
        self$`timestamp` <- TxAccountObject$`timestamp`
      }
      if (!is.null(TxAccountObject$`values`)) {
        valuesObject <- Values$new()
        valuesObject$fromJSON(jsonlite::toJSON(TxAccountObject$values, auto_unbox = TRUE, digits = NA))
        self$`values` <- valuesObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`currency_type`)) {
        sprintf(
        '"currency_type":
          "%s"
                ',
        self$`currency_type`
        )},
        if (!is.null(self$`tx_hash`)) {
        sprintf(
        '"tx_hash":
          "%s"
                ',
        self$`tx_hash`
        )},
        if (!is.null(self$`height`)) {
        sprintf(
        '"height":
          %d
                ',
        self$`height`
        )},
        if (!is.null(self$`timestamp`)) {
        sprintf(
        '"timestamp":
          %d
                ',
        self$`timestamp`
        )},
        if (!is.null(self$`values`)) {
        sprintf(
        '"values":
        %s
        ',
        jsonlite::toJSON(self$`values`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(TxAccountJson) {
      TxAccountObject <- jsonlite::fromJSON(TxAccountJson)
      self$`currency_type` <- TxAccountObject$`currency_type`
      self$`tx_hash` <- TxAccountObject$`tx_hash`
      self$`height` <- TxAccountObject$`height`
      self$`timestamp` <- TxAccountObject$`timestamp`
      self$`values` <- Values$new()$fromJSON(jsonlite::toJSON(TxAccountObject$values, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)

