# GraphSense API
#
# GraphSense API
#
# The version of the OpenAPI document: 0.5
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title TxAccount
#'
#' @description TxAccount Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field height  integer 
#'
#' @field timestamp  integer 
#'
#' @field tx_hash  character 
#'
#' @field tx_type  character 
#'
#' @field value  \link{Values} 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
TxAccount <- R6::R6Class(
  'TxAccount',
  public = list(
    `height` = NULL,
    `timestamp` = NULL,
    `tx_hash` = NULL,
    `tx_type` = NULL,
    `value` = NULL,
    initialize = function(
        `height`, `timestamp`, `tx_hash`, `tx_type`, `value`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`height`)) {
        stopifnot(is.numeric(`height`), length(`height`) == 1)
        self$`height` <- `height`
      }
      if (!missing(`timestamp`)) {
        stopifnot(is.numeric(`timestamp`), length(`timestamp`) == 1)
        self$`timestamp` <- `timestamp`
      }
      if (!missing(`tx_hash`)) {
        stopifnot(is.character(`tx_hash`), length(`tx_hash`) == 1)
        self$`tx_hash` <- `tx_hash`
      }
      if (!missing(`tx_type`)) {
        stopifnot(is.character(`tx_type`), length(`tx_type`) == 1)
        self$`tx_type` <- `tx_type`
      }
      if (!missing(`value`)) {
        stopifnot(R6::is.R6(`value`))
        self$`value` <- `value`
      }
    },
    toJSON = function() {
      TxAccountObject <- list()
      if (!is.null(self$`height`)) {
        TxAccountObject[['height']] <-
          self$`height`
      }
      if (!is.null(self$`timestamp`)) {
        TxAccountObject[['timestamp']] <-
          self$`timestamp`
      }
      if (!is.null(self$`tx_hash`)) {
        TxAccountObject[['tx_hash']] <-
          self$`tx_hash`
      }
      if (!is.null(self$`tx_type`)) {
        TxAccountObject[['tx_type']] <-
          self$`tx_type`
      }
      if (!is.null(self$`value`)) {
        TxAccountObject[['value']] <-
          self$`value`$toJSON()
      }

      TxAccountObject
    },
    fromJSON = function(TxAccountJson) {
      TxAccountObject <- jsonlite::fromJSON(TxAccountJson)
      if (!is.null(TxAccountObject$`height`)) {
        self$`height` <- TxAccountObject$`height`
      }
      if (!is.null(TxAccountObject$`timestamp`)) {
        self$`timestamp` <- TxAccountObject$`timestamp`
      }
      if (!is.null(TxAccountObject$`tx_hash`)) {
        self$`tx_hash` <- TxAccountObject$`tx_hash`
      }
      if (!is.null(TxAccountObject$`tx_type`)) {
        self$`tx_type` <- TxAccountObject$`tx_type`
      }
      if (!is.null(TxAccountObject$`value`)) {
        valueObject <- Values$new()
        valueObject$fromJSON(jsonlite::toJSON(TxAccountObject$value, auto_unbox = TRUE, digits = NA))
        self$`value` <- valueObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`height`)) {
        sprintf(
        '"height":
          %d
                ',
        self$`height`
        )},
        if (!is.null(self$`timestamp`)) {
        sprintf(
        '"timestamp":
          %d
                ',
        self$`timestamp`
        )},
        if (!is.null(self$`tx_hash`)) {
        sprintf(
        '"tx_hash":
          "%s"
                ',
        self$`tx_hash`
        )},
        if (!is.null(self$`tx_type`)) {
        sprintf(
        '"tx_type":
          "%s"
                ',
        self$`tx_type`
        )},
        if (!is.null(self$`value`)) {
        sprintf(
        '"value":
        %s
        ',
        jsonlite::toJSON(self$`value`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(TxAccountJson) {
      TxAccountObject <- jsonlite::fromJSON(TxAccountJson)
      self$`height` <- TxAccountObject$`height`
      self$`timestamp` <- TxAccountObject$`timestamp`
      self$`tx_hash` <- TxAccountObject$`tx_hash`
      self$`tx_type` <- TxAccountObject$`tx_type`
      self$`value` <- Values$new()$fromJSON(jsonlite::toJSON(TxAccountObject$value, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)

