# GraphSense API
#
# GraphSense API
#
# The version of the OpenAPI document: 0.5
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Txs
#'
#' @description Txs Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field next_page  character [optional]
#'
#' @field txs  list( \link{Tx} ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Txs <- R6::R6Class(
  'Txs',
  public = list(
    `next_page` = NULL,
    `txs` = NULL,
    initialize = function(
        `next_page`=NULL, `txs`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`next_page`)) {
        stopifnot(is.character(`next_page`), length(`next_page`) == 1)
        self$`next_page` <- `next_page`
      }
      if (!is.null(`txs`)) {
        stopifnot(is.vector(`txs`), length(`txs`) != 0)
        sapply(`txs`, function(x) stopifnot(R6::is.R6(x)))
        self$`txs` <- `txs`
      }
    },
    toJSON = function() {
      TxsObject <- list()
      if (!is.null(self$`next_page`)) {
        TxsObject[['next_page']] <-
          self$`next_page`
      }
      if (!is.null(self$`txs`)) {
        TxsObject[['txs']] <-
          lapply(self$`txs`, function(x) x$toJSON())
      }

      TxsObject
    },
    fromJSON = function(TxsJson) {
      TxsObject <- jsonlite::fromJSON(TxsJson)
      if (!is.null(TxsObject$`next_page`)) {
        self$`next_page` <- TxsObject$`next_page`
      }
      if (!is.null(TxsObject$`txs`)) {
        self$`txs` <- ApiClient$new()$deserializeObj(TxsObject$`txs`, "array[Tx]", loadNamespace("openapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`next_page`)) {
        sprintf(
        '"next_page":
          "%s"
                ',
        self$`next_page`
        )},
        if (!is.null(self$`txs`)) {
        sprintf(
        '"txs":
        [%s]
',
        paste(sapply(self$`txs`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(TxsJson) {
      TxsObject <- jsonlite::fromJSON(TxsJson)
      self$`next_page` <- TxsObject$`next_page`
      self$`txs` <- ApiClient$new()$deserializeObj(TxsObject$`txs`, "array[Tx]", loadNamespace("openapi"))
      self
    }
  )
)

