# GraphSense API
#
# GraphSense API
#
# The version of the OpenAPI document: 0.5
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title TxsAccount
#'
#' @description TxsAccount Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field next_page  character [optional]
#'
#' @field txs  list( \link{TxAccount} ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
TxsAccount <- R6::R6Class(
  'TxsAccount',
  public = list(
    `next_page` = NULL,
    `txs` = NULL,
    initialize = function(
        `next_page`=NULL, `txs`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`next_page`)) {
        stopifnot(is.character(`next_page`), length(`next_page`) == 1)
        self$`next_page` <- `next_page`
      }
      if (!is.null(`txs`)) {
        stopifnot(is.vector(`txs`), length(`txs`) != 0)
        sapply(`txs`, function(x) stopifnot(R6::is.R6(x)))
        self$`txs` <- `txs`
      }
    },
    toJSON = function() {
      TxsAccountObject <- list()
      if (!is.null(self$`next_page`)) {
        TxsAccountObject[['next_page']] <-
          self$`next_page`
      }
      if (!is.null(self$`txs`)) {
        TxsAccountObject[['txs']] <-
          lapply(self$`txs`, function(x) x$toJSON())
      }

      TxsAccountObject
    },
    fromJSON = function(TxsAccountJson) {
      TxsAccountObject <- jsonlite::fromJSON(TxsAccountJson)
      if (!is.null(TxsAccountObject$`next_page`)) {
        self$`next_page` <- TxsAccountObject$`next_page`
      }
      if (!is.null(TxsAccountObject$`txs`)) {
        self$`txs` <- ApiClient$new()$deserializeObj(TxsAccountObject$`txs`, "array[TxAccount]", loadNamespace("openapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`next_page`)) {
        sprintf(
        '"next_page":
          "%s"
                ',
        self$`next_page`
        )},
        if (!is.null(self$`txs`)) {
        sprintf(
        '"txs":
        [%s]
',
        paste(sapply(self$`txs`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(TxsAccountJson) {
      TxsAccountObject <- jsonlite::fromJSON(TxsAccountJson)
      self$`next_page` <- TxsAccountObject$`next_page`
      self$`txs` <- ApiClient$new()$deserializeObj(TxsAccountObject$`txs`, "array[TxAccount]", loadNamespace("openapi"))
      self
    }
  )
)

